/* Türk dili tərcümələri (açar = Azərbaycanca mənbə mətni). Yeni mətn əlavə edəndə: node tools/i18n-scan.js --missing və npm test. */
(function (root) {
  'use strict';
  root.I18n.add('tr', {
    "Kassa": "Kasa",
    "Qaytarma": "İade",
    "Məhsullar": "Ürünler",
    "Təchizatçılar": "Tedarikçiler",
    "Çeklər": "Fişler",
    "Növbə": "Vardiya",
    "İcazələr": "İzinler",
    "Bu rol üçün açıq ekran yoxdur.": "Bu rol için erişilebilir ekran yok.",
    "Onlayn": "Çevrimiçi",
    "Oflayn": "Çevrimdışı",
    "Google Apps Script serverinin orta cavab müddəti. Cihazlar arasında yenilik təxminən bunun 2–3 qatı qədər gecikir": "Google Apps Script sunucusunun ortalama yanıt süresi. Cihazlar arası güncelleme yaklaşık bunun 2–3 katı kadar gecikir.",
    "Server {0} san": "Sunucu {0} sn",
    "Tətbiq versiyası. İki cihazda eyni olmalıdır; fərqlidirsə Ctrl+F5 basın": "Uygulama sürümü. İki cihazda aynı olmalı; farklıysa Ctrl+F5'e basın",
    "Serverə göndərilməmiş qeydlər": "Sunucuya gönderilmemiş kayıtlar",
    "{0} sinxron gözləyir": "{0} kayıt senkron bekliyor",
    "Sinxron xətası": "Senkron hatası",
    "Sorğular ({0})": "İstekler ({0})",
    "Növbə açıq · {0}": "Vardiya açık · {0}",
    "Növbə bağlı": "Vardiya kapalı",
    "Təsdiq sorğusu gələndə telefona/brauzerə bildiriş": "Onay isteği geldiğinde telefona/tarayıcıya bildirim",
    "Bildiriş": "Bildirim",
    "Bu cihazın printeri: kağız eni, etiket ölçüsü, test çapı": "Bu cihazın yazıcısı: kâğıt genişliği, etiket boyutu, deneme baskısı",
    "Çap": "Yazdır",
    "Çıxış": "Çıkış",
    "Yeni təsdiq sorğusu: {0}": "Yeni onay isteği: {0}",
    "Hesabınız dəyişdirilib və ya söndürülüb. Yenidən daxil olun": "Hesabınız değiştirildi veya devre dışı bırakıldı. Yeniden giriş yapın",
    "Bölmələr": "Bölümler",
    "7BOXS — Kassa": "7BOXS — Kasa",
    "Başlatma xətası: {0}": "Başlatma hatası: {0}",
    "Bildiriş yalnız təhlükəsiz (https) ünvanda işləyir": "Bildirimler yalnızca güvenli (https) adreste çalışır",
    "iPhone/iPad-də bildiriş yalnız tətbiq ana ekrana əlavə edilibsə işləyir: Safari → Paylaş → \"Ana ekrana əlavə et\", sonra oradan açın (iOS 16.4 və yuxarı)": "iPhone/iPad'de bildirim yalnızca uygulama ana ekrana eklenmişse çalışır: Safari → Paylaş → \"Ana Ekrana Ekle\", sonra oradan açın (iOS 16.4 ve üstü)",
    "Bu brauzer bildirişi dəstəkləmir. Chrome, Edge və ya Firefox-un yeni versiyasından istifadə edin": "Bu tarayıcı bildirimi desteklemiyor. Chrome, Edge veya Firefox'un yeni bir sürümünü kullanın",
    "Xidmət işçisi (service worker) işləmir. Səhifəni yeniləyin (Ctrl+F5); tətbiq https ünvanından açılmalıdır": "Hizmet işçisi (service worker) çalışmıyor. Sayfayı yenileyin (Ctrl+F5); uygulama https adresinden açılmalıdır",
    "Server skripti köhnədir: Code.gs-in v6 versiyasını yapışdırın, setup() işlədin və \"New version\" deploy edin": "Sunucu betiği eski: Code.gs'in v6 sürümünü yapıştırın, setup() çalıştırın ve \"New version\" deploy edin",
    "Apps Script-də V8 runtime aktiv deyil (BigInt yoxdur): Project Settings → \"Chrome V8 runtime\" seçin, sonra New version deploy edin. Sinxron təsirlənmir, yalnız bildiriş işləmir": "Apps Script'te V8 runtime etkin değil (BigInt yok): Project Settings → \"Chrome V8 runtime\" seçin, sonra New version deploy edin. Senkron etkilenmez, yalnızca bildirim çalışmaz",
    "Apps Script-ə xarici sorğu icazəsi verilməyib: redaktorda setup() işlədin, \"Connect to an external service\" icazəsini təsdiqləyin və yenidən \"New version\" deploy edin": "Apps Script'e harici istek izni verilmemiş: editörde setup() çalıştırın, \"Connect to an external service\" iznini onaylayın ve yeniden \"New version\" deploy edin",
    "Əvvəl serveri qoşun (İcazələr → Mağaza və server)": "Önce sunucuyu bağlayın (İzinler → Mağaza ve sunucu)",
    "Daxil olun": "Giriş yapın",
    "Bildiriş bloklanıb. Brauzerin ünvan sətrindəki qıfıl işarəsi → Bildirişlər → \"İcazə ver\", sonra yenidən basın": "Bildirim engellenmiş. Tarayıcı adres çubuğundaki kilit simgesi → Bildirimler → \"İzin ver\", sonra yeniden basın",
    "Bildiriş icazəsi verilmədi": "Bildirim izni verilmedi",
    "Bu rolun təsdiq sorğusu almaq icazəsi yoxdur": "Bu rolün onay isteği alma izni yok",
    "Təsdiq sorğusu": "Onay isteği",
    "Kassadan menecer təsdiqi gözlənilir": "Kasiyer yönetici onayını bekliyor",
    "7BOXS — test": "7BOXS — test",
    "Bildirişlər bu cihazda işləyir.": "Bildirimler bu cihazda çalışıyor.",
    "Bu cihaz push üçün qoşulmayıb. \"Aktiv et\" düyməsini basın": "Bu cihaz push için bağlı değil. \"Etkinleştir\" düğmesine basın",
    "Kassir təsdiq sorğusu göndərəndə (sətir silmə, endirim, qaytarma) bu cihaza bildiriş gəlsin. Hər menecer cihazında bir dəfə aktiv edilir.": "Kasiyer onay isteği gönderdiğinde (satır silme, indirim, iade) bu cihaza bildirim gelir. Her yönetici cihazında bir kez etkinleştirilir.",
    "Brauzer icazəsi verilib": "Tarayıcı izni verildi",
    "Brauzer bildirişi bloklayıb (ünvan sətrindəki qıfıldan açın)": "Tarayıcı bildirimi engelledi (adres çubuğundaki kilitten açın)",
    "Brauzer icazəsi hələ verilməyib": "Tarayıcı izni henüz verilmedi",
    "Bu cihaz bildirişə qoşulub": "Bu cihaz bildirime bağlı",
    "Bu cihaz bildirişə qoşulmayıb": "Bu cihaz bildirime bağlı değil",
    "Bu rolun təsdiq sorğusu almaq icazəsi yoxdur (Menecer və ya Admin daxil olmalıdır)": "Bu rolün onay isteği alma izni yok (Yönetici veya Admin olarak girin)",
    "Test bildirişi göndər": "Test bildirimi gönder",
    "Söndür": "Devre dışı bırak",
    "Bildiriş aktiv edildi": "Bildirim etkinleştirildi",
    "Aktiv et": "Etkinleştir",
    "Göndərilir…": "Gönderiliyor…",
    "Bu cihazda bildiriş göstərildi (ikon və səs yoxlanılır)": "Bu cihazda bildirim gösterildi (simge ve ses kontrol edilir)",
    "Bu cihazda bildiriş göstərilmədi: {0}": "Bu cihazda bildirim gösterilmedi: {0}",
    "naməlum səbəb": "bilinmeyen neden",
    "Server push xidmətinə göndərdi (cavab {0}). 5–15 saniyəyə \"Təsdiq sorğusu\" bildirişi gəlməlidir; tətbiqi başqa tabə keçirin": "Sunucu push hizmetine gönderdi (yanıt {0}). 5–15 saniye içinde \"Onay isteği\" bildirimi gelmeli; başka bir sekmeye geçin",
    "Push xidməti rədd etdi (cavab {0}): {1}. Söndürüb yenidən aktiv edin": "Push hizmeti reddetti (yanıt {0}): {1}. Kapatıp yeniden etkinleştirin",
    "Bildirişlər": "Bildirimler",
    "Bağla": "Kapat",
    "Yarımçıq çek bərpa olundu ({0} sətir)": "Yarım kalan fiş geri yüklendi ({0} satır)",
    "\"{0}\" qalığı yoxdur və limit ({1} mənfi çek) dolub. Satmaq olmaz — mal qəbulu lazımdır (qəbulu menecer edir).": "\"{0}\" stokta yok ve sınır ({1} eksi stoklu fiş) doldu. Satılamaz — mal kabulü gerekli (kabulü yönetici yapar).",
    "Diqqət: \"{0}\" qalığı {1}. Mənfi qalıqla satış {2}/{3} çek.": "Dikkat: \"{0}\" stoğu {1}. Eksi stoklu satış {2}/{3} fiş.",
    "{0} əlavə olundu": "{0} eklendi",
    "Bu istehsalçı barkodudur. Məhsulun üzərindəki mağaza barkodunu oxudun ({0}).": "Bu üretici barkodu. Ürünün üzerindeki mağaza barkodunu okutun ({0}).",
    "Bu çek barkodudur. Qaytarma üçün \"Qaytarma\" bölməsinə keçin.": "Bu fiş barkodu. İade için \"İade\" bölümüne geçin.",
    "\"{0}\" satışdan çıxarılıb.": "\"{0}\" satıştan kaldırılmış.",
    "Barkod tapılmadı: {0}": "Barkod bulunamadı: {0}",
    "Sayı 1-dən azaltmaq olmaz. Sətri silmək üçün zibil ikonuna basın (menecer təsdiqi lazımdır).": "Adet 1'in altına düşürülemez. Satırı silmek için çöp kutusu simgesine basın (yönetici onayı gerekir).",
    "Bu sətir üçün sorğu artıq göndərilib, menecer cavabı gözlənilir": "Bu satır için istek zaten gönderildi, yönetici yanıtı bekleniyor",
    "Sətri çekdən sil": "Satırı fişten sil",
    "{0} çekdən çıxarılır.": "{0} fişten çıkarılıyor.",
    "{0} sətir silmək istəyir: {1}": "{0} satır silmek istiyor: {1}",
    "Təsdiq olunan {0} ədəd silindi, sətirdə {1} qaldı ({2} təsdiqlədi)": "Onaylanan {0} adet silindi, satırda {1} kaldı ({2} onayladı)",
    "Sətir silindi ({0} təsdiqlədi)": "Satır silindi ({0} onayladı)",
    "Çekin ləğvi üçün sorğu artıq göndərilib": "Fişin iptali için istek zaten gönderildi",
    "Çeki ləğv et": "Fişi iptal et",
    "Bütün çek ({0} ₼) ləğv olunur.": "Tüm fiş ({0} ₼) iptal ediliyor.",
    "{0} çeki ləğv etmək istəyir: {1} ₼": "{0} fişi iptal etmek istiyor: {1} ₼",
    "Çek arada dəyişdi, təsdiq olunmuş ləğv tətbiq edilmədi": "Fiş arada değişti, onaylanan iptal uygulanmadı",
    "Endirim sorğusu": "İndirim isteği",
    "Endirim, % (ən çox {0}%)": "İndirim, % (en fazla {0}%)",
    "Endirimi götür": "İndirimi kaldır",
    "İmtina": "Vazgeç",
    "Menecerə göndər": "Yöneticiye gönder",
    "{0}% endirim: {1} → {2} ₼": "%{0} indirim: {1} → {2} ₼",
    "Endirimi təsdiqlə": "İndirimi onayla",
    "{0} endirim istəyir: {1}% endirim: {2} → {3} ₼": "{0} indirim istiyor: %{1}: {2} → {3} ₼",
    "Çek arada dəyişdi, təsdiqlənmiş endirim tətbiq edilmədi. Yenidən sorğu göndərin": "Fiş arada değişti, onaylanan indirim uygulanmadı. İsteği yeniden gönderin",
    "{0}% endirim təsdiqləndi ({1})": "%{0} indirim onaylandı ({1})",
    "Endirim təsdiqlənmədi": "İndirim onaylanmadı",
    "Çek № {0} tamamlandı{1}{2}": "Fiş No {0} tamamlandı{1}{2}",
    "· qaytarılacaq {0} ₼": "para üstü {0} ₼",
    "· ÇEK ÇAP OLUNMADI ({0}): Çeklər bölməsindən təkrar çap edin": "FİŞ YAZDIRILAMADI ({0}): Fişler bölümünden yeniden yazdırın",
    "məs. say səhv idi, sayım nəticəsi": "örn. sayım hatası, sayım sonucu",
    "Fərqin izahı (əvvəlki növbənin qalığından fərqlidir)": "Farkın açıklaması (önceki vardiyanın kalanından farklı)",
    "Məbləğ səhvdir": "Tutar hatalı",
    "Yoxlanılır…": "Kontrol ediliyor…",
    "Növbə açıldı": "Vardiya açıldı",
    "Növbəni aç": "Vardiyayı aç",
    "Növbə bağlıdır": "Vardiya kapalı",
    "Satışa başlamaq üçün kassadakı başlanğıc nağdı sayıb yazın.": "Satışa başlamak için kasadaki başlangıç nakdini sayıp yazın.",
    "Əvvəlki növbədən kassada qalan nağd: {0} ₼ ({1}). Növbə bu məbləğlə başlayır; kassanı sayıb fərqli çıxsa dəyişin və izah yazın.": "Önceki vardiyadan kasada kalan nakit: {0} ₼ ({1}). Vardiya bu tutarla başlar; sayımda fark çıkarsa değiştirin ve açıklama yazın.",
    "Başlanğıc nağd, ₼": "Başlangıç nakdi, ₼",
    "Barkodu oxudun — məhsul burada görünəcək": "Barkodu okutun — ürün burada görünecek",
    "Qalıq yoxdur, limit dolub — satılmaz": "Stok yok, sınır doldu — satılamaz",
    "Qalıq {0} · mənfi qalıqla satış {1}/{2}": "Stok {0} · eksi stoklu satış {1}/{2}",
    "Azalt": "Azalt",
    "Sətri silmək üçün zibil ikonu (menecer təsdiqi)": "Satırı silmek için çöp kutusu simgesi (yönetici onayı)",
    "Sayı azalt": "Adedi azalt",
    "Artır": "Artır",
    "{0} ədəd": "{0} adet",
    "Menecer cavabı gözlənilir": "Yönetici yanıtı bekleniyor",
    "Sətri sil (menecer təsdiqi lazımdır)": "Satırı sil (yönetici onayı gerekir)",
    "Sətri sil: {0}": "Satırı sil: {0}",
    "Nağd ödəniş": "Nakit ödeme",
    "Bank ödənişi": "Banka ödemesi",
    "Qarışıq ödəniş": "Karma ödeme",
    "Bank növü": "Banka ödeme türü",
    "POS kart": "POS kart",
    "Karta köçürmə": "Karta havale",
    "Bank hissəsi, ₼": "Banka kısmı, ₼",
    "Müştəridən alınan nağd, ₼ (boş qoysanız — dəqiq nağd hissə)": "Müşteriden alınan nakit, ₼ (boş bırakırsanız — tam nakit kısmı)",
    "Müştəridən alınan nağd, ₼": "Müşteriden alınan nakit, ₼",
    "Dəqiq məbləğ": "Tam tutar",
    "Terminalda / bank tətbiqində {0} ₼ ödənişin keçdiyini yoxlayın, sonra təsdiqləyin.": "Terminalde / banka uygulamasında {0} ₼ ödemenin geçtiğini kontrol edin, sonra onaylayın.",
    "Yazılır…": "Kaydediliyor…",
    "Təsdiqlə və çek çap et (Enter)": "Onayla ve fişi yazdır (Enter)",
    "Nağd hissə: {0} ₼": "Nakit kısmı: {0} ₼",
    "Qaytarılacaq": "Para üstü",
    "Məhsul": "Ürün",
    "Mağaza barkodu": "Mağaza barkodu",
    "Say": "Adet",
    "Qiymət": "Fiyat",
    "Cəm": "Tutar",
    "Sil": "Sil",
    "Endirim (F4)": "İndirim (F4)",
    "Ləğv (Esc)": "İptal (Esc)",
    "Çek": "Fiş",
    "↑/↓ sətir seçimi · + / − say · Del və ya zibil ikonu: sətri silmək (menecer təsdiqi: PIN və ya sorğu).": "↑/↓ satır seçimi · + / − adet · Del veya çöp kutusu simgesi: satırı silmek (yönetici onayı: PIN veya istek).",
    "Ödəniş": "Ödeme",
    "Ara cəm": "Ara toplam",
    "Endirim": "İndirim",
    "Yekun": "Toplam",
    "Nağd": "Nakit",
    "Bank": "Banka",
    "Qarışıq": "Karma",
    "Nağd alınan": "Alınan nakit",
    "Qaytarılan": "İade edilen",
    "DUBLİKAT": "KOPYA",
    "VÖEN": "VÖEN",
    "Çek №": "Fiş No",
    "Tarix": "Tarih",
    "Kassir": "Kasiyer",
    "Endirim {0}%": "İndirim %{0}",
    "YEKUN": "TOPLAM",
    "Qaytarma {0} gün ərzində, çeklə": "İade {0} gün içinde, fişle",
    "Bu çek fiskal çek deyil": "Bu fiş mali fiş değildir",
    "QAYTARMA ÇEKİ": "İADE FİŞİ",
    "İlkin çek №": "Asıl fiş No",
    "Təsdiqləyən": "Onaylayan",
    "ÇAP SINAĞI": "DENEME BASKISI",
    "Kağız {0} mm · çap sahəsi {1} mm": "Kâğıt {0} mm · baskı alanı {1} mm",
    "← bütün çərçivə görünməlidir →": "← çerçevenin tamamı görünmeli →",
    "{0} dpi · zolaq {1} mm": "{0} dpi · çubuk {1} mm",
    "80 mm (XP-80, XP-N160 …)": "80 mm (XP-80, XP-N160 …)",
    "58 mm (XP-58 …)": "58 mm (XP-58 …)",
    "203 dpi (adətən)": "203 dpi (genellikle)",
    "300 dpi": "300 dpi",
    "Tətbiq kağız ölçüsünü verir (tövsiyə)": "Kâğıt boyutunu uygulama belirler (önerilen)",
    "Çap sürücüsünün ölçüsü": "Yazıcı sürücüsünün boyutu",
    "Digər ölçü…": "Diğer boyut…",
    "203 dpi (XP-365B, XP-420B …)": "203 dpi (XP-365B, XP-420B …)",
    "Tətbiq etiket ölçüsünü verir (tövsiyə)": "Etiket boyutunu uygulama belirler (önerilen)",
    "En, mm": "Genişlik, mm",
    "Hündürlük, mm": "Yükseklik, mm",
    "Etiketdə barkod zolağı: {0} mm ({1} nöqtə), eni {2} mm.{3}": "Etiketteki barkod çubuğu: {0} mm ({1} nokta), genişlik {2} mm.{3}",
    "Etiket çox dardır: barkod oxunmaya bilər, daha geniş etiket seçin.": "Etiket çok dar: barkod okunmayabilir, daha geniş etiket seçin.",
    "Çap ayarları (bu cihaz üçün)": "Yazdırma ayarları (bu cihaz için)",
    "Çek printeri (termo)": "Fiş yazıcısı (termal)",
    "Kağız eni": "Kâğıt genişliği",
    "Çap sıxlığı": "Baskı çözünürlüğü",
    "Kağız ölçüsü": "Kâğıt boyutu",
    "Çekdən sonra boşluq, mm": "Fişten sonra boşluk, mm",
    "Çekin dili": "Fiş dili",
    "Test çeki çap et": "Test fişi yazdır",
    "Etiket printeri": "Etiket yazıcısı",
    "Etiket ölçüsü": "Etiket boyutu",
    "Test etiketi çap et": "Test etiketi yazdır",
    "Çap pəncərəsində: Printer — Xprinter, Miqyas — 100%, Kənar boşluqlar — Yoxdur, Başlıq və sonluq — söndürülü. Test çapında çərçivə tam görünmürsə, kənar boşluğu və ya \"Kağız ölçüsü\" seçimini dəyişin.": "Yazdırma penceresinde: Yazıcı — Xprinter, Ölçek — %100, Kenar boşlukları — Yok, Üst ve alt bilgi — kapalı. Deneme baskısında çerçeve tam görünmüyorsa kenar boşluğunu veya \"Kâğıt boyutu\" seçeneğini değiştirin.",
    "Yadda saxla": "Kaydet",
    "Çap ayarları yadda saxlanıldı": "Yazdırma ayarları kaydedildi",
    "Eyni mağaza barkodu iki məhsulda: \"{0}\" və \"{1}\" ({2})": "Aynı mağaza barkodu iki üründe: \"{0}\" ve \"{1}\" ({2})",
    "Çek № {0} iki cihazda verilib (hər ikisi saxlanıldı)": "Fiş No {0} iki cihazda verilmiş (ikisi de saklandı)",
    "Hadisə tətbiq olunmadı ({0}): {1}": "Olay uygulanamadı ({0}): {1}",
    "Etibarsız hadisə rədd edildi ({0})": "Geçersiz olay reddedildi ({0})",
    "Bu səhifə çərçivə içində açıla bilməz": "Bu sayfa bir çerçeve içinde açılamaz",
    "Satış etmək": "Satış yapmak",
    "Endirimi təsdiqləmək": "İndirimi onaylamak",
    "Çekdən sətir silmək": "Fişten satır silmek",
    "Qaytarma sorğusu": "İade isteği",
    "Qaytarmanı təsdiqləmək": "İadeyi onaylamak",
    "Növbə açıb bağlamaq": "Vardiya açıp kapatmak",
    "Məhsullara baxmaq": "Ürünleri görüntülemek",
    "Məhsul yaratmaq və dəyişmək": "Ürün oluşturmak ve değiştirmek",
    "Mal qəbul etmək (qalığı artırmaq)": "Mal kabul etmek (stoğu artırmak)",
    "Satış qiymətini təyin etmək": "Satış fiyatını belirlemek",
    "Alış qiymətini görmək": "Alış fiyatını görmek",
    "Etiket çap etmək": "Etiket yazdırmak",
    "Hesabatlara baxmaq": "Raporları görüntülemek",
    "Təchizatçılara və təchizatçı hesabatına baxmaq": "Tedarikçileri ve tedarikçi raporunu görüntülemek",
    "Təchizatçı əlavə etmək və dəyişmək": "Tedarikçi eklemek ve değiştirmek",
    "İstifadəçiləri idarə etmək": "Kullanıcıları yönetmek",
    "İcazə matrisini dəyişmək": "İzin matrisini değiştirmek",
    "Admin": "Admin",
    "Menecer": "Yönetici",
    "Mühasib": "Muhasebeci",
    "Endirim faizi 0-dan böyük olmalıdır": "İndirim yüzdesi 0'dan büyük olmalıdır",
    "Endirim {0}%-dən çox ola bilməz": "İndirim %{0}'den fazla olamaz",
    "Çek boşdur": "Fiş boş",
    "Alınan məbləği yazın": "Alınan tutarı yazın",
    "Alınan məbləğ yekundan azdır": "Alınan tutar toplamdan az",
    "POS kart və ya köçürmə seçin": "POS kart veya havale seçin",
    "Bank hissəsinin növünü seçin": "Banka kısmının türünü seçin",
    "Bank hissəsini yazın": "Banka kısmını yazın",
    "Bank hissəsi yekundan az olmalıdır, əks halda \"Bank\" seçin": "Banka kısmı toplamdan az olmalı, aksi halde \"Banka\" seçin",
    "Nağd alınan məbləğ nağd hissədən azdır": "Alınan nakit, nakit kısmından az",
    "Ödəniş üsulu seçilməyib": "Ödeme yöntemi seçilmedi",
    "İstifadəçi": "Kullanıcı",
    "Daxil ol": "Giriş yap",
    "Mağaza idarəetmə sistemi": "Mağaza yönetim sistemi",
    "PIN": "PIN",
    "İstifadəçini seçin": "Kullanıcıyı seçin",
    "Server qoşulub · istifadəçilər və məlumat avtomatik yenilənir": "Sunucu bağlı · kullanıcılar ve veriler otomatik güncellenir",
    "Bu cihazı serverə qoş": "Bu cihazı sunucuya bağla",
    "Başqa cihazda artıq işləyirsinizsə, bunu edin: istifadəçilər, məhsullar və çeklər oradan yüklənəcək.": "Başka bir cihazda zaten çalışıyorsanız bunu yapın: kullanıcılar, ürünler ve fişler oradan yüklenecek.",
    "Ünvanı və açarı (SYNC_TOKEN) yazın. Məlumat serverdən yüklənəcək, bir neçə saniyə çəkə bilər.": "Adresi ve anahtarı (SYNC_TOKEN) yazın. Veriler sunucudan yüklenecek, birkaç saniye sürebilir.",
    "Apps Script veb tətbiq ünvanı": "Apps Script web uygulaması adresi",
    "Sinxron açarı": "Senkron anahtarı",
    "Qoş və yüklə": "Bağla ve yükle",
    "Yoxlanılır və yüklənir…": "Kontrol ediliyor ve yükleniyor…",
    "Qoşuldu · {0} qeyd yükləndi": "Bağlandı · {0} kayıt yüklendi",
    "Yeni PIN təyin edin": "Yeni PIN belirleyin",
    "İşə başlamazdan əvvəl yalnız sizə məlum olan 4–8 rəqəmli PIN seçin.": "Başlamadan önce yalnızca sizin bildiğiniz 4–8 haneli bir PIN seçin.",
    "Hazırkı PIN": "Mevcut PIN",
    "Yeni PIN": "Yeni PIN",
    "Yeni PIN təkrar": "Yeni PIN tekrar",
    "Saxla və davam et": "Kaydet ve devam et",
    "Yeni PIN-lər eyni deyil": "Yeni PIN'ler aynı değil",
    "PIN dəyişdirildi": "PIN değiştirildi",
    "Təsdiq sorğuları": "Onay istekleri",
    "Gözləyən sorğu yoxdur.": "Bekleyen istek yok.",
    "Təsdiqləndi": "Onaylandı",
    "Rədd edildi": "Reddedildi",
    "Rədd et": "Reddet",
    "Təsdiqlə": "Onayla",
    "Ad, mağaza və ya istehsalçı barkodu": "Ad, mağaza veya üretici barkodu",
    "Nümunə məhsullar əlavə olundu": "Örnek ürünler eklendi",
    "Sınaq üçün nümunə məhsullar əlavə et": "Deneme için örnek ürünler ekle",
    "Uyğun məhsul yoxdur": "Uygun ürün yok",
    "Hələ məhsul yoxdur": "Henüz ürün yok",
    "köhnə qalıq": "eski stok",
    "Aktiv": "Aktif",
    "Passiv": "Pasif",
    "Dəyiş": "Değiştir",
    "Qəbul": "Kabul",
    "Partiyalar": "Partiler",
    "Etiket": "Etiket",
    "Axtarış": "Ara",
    "Yeni məhsul": "Yeni ürün",
    "İstehsalçı barkodu": "Üretici barkodu",
    "Satış ₼": "Satış ₼",
    "Orta maya ₼": "Ort. maliyet ₼",
    "Qalıq": "Stok",
    "Təchizatçı (qalıq)": "Tedarikçi (stok)",
    "Status": "Durum",
    "Ad *": "Ad *",
    "Kateqoriya": "Kategori",
    "Brend": "Marka",
    "Yaş qrupu": "Yaş grubu",
    "məs. 3+": "örn. 3+",
    "İstehsalçı barkodu (nəzarət üçün, uzunluq məhdud deyil)": "Üretici barkodu (kontrol için, uzunluk sınırsız)",
    "Satış qiyməti, ₼ *": "Satış fiyatı, ₼ *",
    "Alış qiyməti, ₼": "Alış fiyatı, ₼",
    "Minimum qalıq": "Minimum stok",
    "Satış qiymətini yalnız Menecer və Admin təyin edir.": "Satış fiyatını yalnızca Yönetici ve Admin belirler.",
    "Mağaza barkodu:": "Mağaza barkodu:",
    "(dəyişmir)": "(değişmez)",
    "Mağaza barkodu yadda saxlayanda avtomatik veriləcək.": "Mağaza barkodu kaydedildiğinde otomatik verilecek.",
    "Satışda aktivdir": "Satışta aktif",
    "Məhsulu dəyiş": "Ürünü değiştir",
    "Satış qiyməti səhvdir": "Satış fiyatı hatalı",
    "Alış qiyməti səhvdir": "Alış fiyatı hatalı",
    "Məhsul yaradıldı · {0}": "Ürün oluşturuldu · {0}",
    "Yadda saxlanıldı": "Kaydedildi",
    "Qaimə №, izah": "İrsaliye No, açıklama",
    "— təchizatçı seçin —": "— tedarikçi seçin —",
    "— təchizatçı yoxdur —": "— tedarikçi yok —",
    "FIFO: hər satış ən köhnə partiyadan çıxır, hesabatda təchizatçıya görə görünür.": "FIFO: her satış en eski partiden düşülür, raporda tedarikçiye göre görünür.",
    "Hələ təchizatçı yoxdur. Yeni təchizatçı əlavə edin; təchizatçısız qəbul \"köhnə qalıq\" kimi sayılır.": "Henüz tedarikçi yok. Yeni tedarikçi ekleyin; tedarikçisiz kabul \"eski stok\" sayılır.",
    "+ Yeni təchizatçı": "+ Yeni tedarikçi",
    "Mal qəbulu — {0}": "Mal kabulü — {0}",
    "Hazırkı qalıq: {0}. Hər qəbul ayrıca partiyadır (təchizatçı, say, alış qiyməti).": "Mevcut stok: {0}. Her kabul ayrı bir partidir (tedarikçi, adet, alış fiyatı).",
    "Təchizatçı": "Tedarikçi",
    "Alış qiyməti (ədəd), ₼": "Alış fiyatı (adet), ₼",
    "Qeyd": "Not",
    "Qəbul et": "Kabul et",
    "Təchizatçını seçin": "Tedarikçiyi seçin",
    "Qalıq: {0}": "Stok: {0}",
    "Şirkət və ya şəxs adı": "Şirket veya kişi adı",
    "VÖEN, ünvan, şərtlər…": "VÖEN, adres, şartlar…",
    "Təchizatçını dəyiş": "Tedarikçiyi değiştir",
    "Yeni təchizatçı": "Yeni tedarikçi",
    "Telefon": "Telefon",
    "Partiyalar (FIFO) — {0}": "Partiler (FIFO) — {0}",
    "Bu məhsul üzrə qəbul yoxdur.": "Bu ürün için kabul yok.",
    "Qəbul tarixi": "Kabul tarihi",
    "Alış ₼": "Alış ₼",
    "Köhnə qalıq": "Eski stok",
    "Təchizatçısız": "Tedarikçisiz",
    "Satış ən köhnə partiyadan çıxır. \"Qalıq\" sütunu hələ satılmamış hissədir.": "Satış en eski partiden düşülür. \"Stok\" sütunu henüz satılmamış kısımdır.",
    "Etiket {0} × {1} mm · {2} dpi · barkod zolağı {3} mm{4}": "Etiket {0} × {1} mm · {2} dpi · barkod çubuğu {3} mm{4}",
    "— etiket dardır, barkod oxunmaya bilər": "— etiket dar, barkod okunmayabilir",
    "Etiket çapı": "Etiket yazdırma",
    "Etiket sayı": "Etiket sayısı",
    "Çap ayarları": "Yazdırma ayarları",
    "Çap et": "Yazdır",
    "Bu ay": "Bu ay",
    "Bu gün": "Bugün",
    "Dünən": "Dün",
    "Keçən ay": "Geçen ay",
    "Bütün vaxt": "Tüm zamanlar",
    "Seçilmiş tarixlər": "Seçilen tarihler",
    "Hələ təchizatçı yoxdur": "Henüz tedarikçi yok",
    "Söndürülüb": "Devre dışı",
    "Redaktə": "Düzenle",
    "Söndürüldü": "Devre dışı bırakıldı",
    "Aktiv edildi": "Etkinleştirildi",
    "Diqqət: {0} ədəd mal satılandan artıq qaytarılıb (məsələn, iki cihaz eyni çekin eyni sətrini oflayn qaytarıb). Qaytarmalar bölməsində həmin çeki yoxlayın; pul iki dəfə qaytarılmış ola bilər.": "Dikkat: {0} adet mal satılandan fazla iade edilmiş (örneğin iki cihaz aynı fişin aynı satırını çevrimdışı iade etmiş). İade bölümünde o fişi kontrol edin; para iki kez iade edilmiş olabilir.",
    "Satılan": "Satılan",
    "Xalis ədəd": "Net adet",
    "Gəlir ₼": "Gelir ₼",
    "Maya (FIFO) ₼": "Maliyet (FIFO) ₼",
    "Mənfəət ₼": "Kâr ₼",
    "Qalıq (ədəd)": "Stok (adet)",
    "Qalığın dəyəri ₼": "Stok değeri ₼",
    "Bu dövrdə məlumat yoxdur": "Bu dönemde veri yok",
    "Cəmi": "Toplam",
    "{0} — məhsullar": "{0} — ürünler",
    "Xalis": "Net",
    "Maya ₼": "Maliyet ₼",
    "Gəlir": "Gelir",
    "Maya (FIFO)": "Maliyet (FIFO)",
    "Mənfəət": "Kâr",
    "Ad": "Ad",
    "Vəziyyət": "Durum",
    "Hansı təchizatçının malından nə qədər satılıb": "Hangi tedarikçinin malından ne kadar satıldı",
    "Excel üçün CSV": "Excel için CSV",
    "Dövr": "Dönem",
    "Başlanğıc": "Başlangıç",
    "Son": "Bitiş",
    "Satış FIFO ilədir: hər çek ən köhnə partiyadan çıxır. Gəlir endirimdən sonrakı məbləğdir, qaytarmalar çıxılır. \"Təchizatçısız\" — sistemə köçməzdən əvvəlki qalıq və ya qəbuldan əvvəl (mənfi qalıqla) satılan mal. Oflayn cihaz sonra sinxronlaşanda bölgü təchizatçılar arasında düzələ bilər, cəmlər dəyişmir.": "Satış FIFO ile gider: her fiş en eski partiden düşülür. Gelir, indirimden sonraki tutardır, iadeler düşülür. \"Tedarikçisiz\" — sisteme geçmeden önceki stok veya kabulden önce (eksi stokla) satılan mal. Çevrimdışı cihaz sonra senkronlandığında tedarikçiler arası dağılım düzelebilir, toplamlar değişmez.",
    "Çek tapılmadı": "Fiş bulunamadı",
    "({0}% endirim)": "(%{0} indirim)",
    "Keçən gün": "Geçen gün",
    "Çekin qaytarma müddəti bitib: {0} gün keçib (limit {1} gün).": "Fişin iade süresi doldu: {0} gün geçti (sınır {1} gün).",
    "Qaytarılan say: {0}": "İade edilecek adet: {0}",
    "\"{0}\": ən çox {1} ədəd qaytarmaq olar (satılıb {2})": "\"{0}\": en fazla {1} adet iade edilebilir (satılan {2})",
    "məs. zədəli, uyğun gəlmədi": "örn. hasarlı, uymadı",
    "Satılıb": "Satıldı",
    "Qaytarılıb": "İade edildi",
    "Qaytarılır": "İade ediliyor",
    "Səbəb": "Neden",
    "Qaytarılacaq say yazın": "İade edilecek adedi yazın",
    "\"{0}\": satılıb {1}, əvvəl qaytarılıb {2} — ən çox {3} ədəd qaytarmaq olar": "\"{0}\": satılan {1}, daha önce iade edilen {2} — en fazla {3} adet iade edilebilir",
    "Çek № {0} üzrə {1} ₼ qaytarılır.": "Fiş No {0} için {1} ₼ iade ediliyor.",
    "Qaytarmanı təsdiqlə": "İadeyi onayla",
    "{0} qaytarma istəyir. Çek № {1} üzrə {2} ₼ qaytarılır.": "{0} iade istiyor. Fiş No {1} için {2} ₼ iade ediliyor.",
    "Qaytarıldı: {0} ₼{1}": "İade edildi: {0} ₼{1}",
    "(nağd {0})": "(nakit {0})",
    "Qaytar": "İade et",
    "Çekin barkodunu oxudun və ya çek nömrəsini yazın": "Fişin barkodunu okutun veya fiş numarasını yazın",
    "Açıq növbə yoxdur. Kassa ekranından açın.": "Açık vardiya yok. Kasa ekranından açın.",
    "Sayılmış məbləği yazın": "Sayılan tutarı yazın",
    "Növbə yoxlanılır və bağlanır…": "Vardiya kontrol ediliyor ve kapatılıyor…",
    "Növbə bağlandı. Fərq: {0} ₼": "Vardiya kapatıldı. Fark: {0} ₼",
    "Bağla və Z hesabatı çap et": "Kapat ve Z raporu yazdır",
    "Açılıb: {0} · {1}": "Açılış: {0} · {1}",
    "Çek sayı": "Fiş sayısı",
    "Satış (endirimdən əvvəl)": "Satış (indirimden önce)",
    "Nağd satış": "Nakit satış",
    "Qaytarmalar": "İadeler",
    "Kassaya mədaxil": "Kasaya giriş",
    "Kassadan məxaric": "Kasadan çıkış",
    "Başlanğıc nağd": "Başlangıç nakdi",
    "Kassada olmalı nağd": "Kasada olması gereken nakit",
    "Növbəni bağla": "Vardiyayı kapat",
    "Sayılmış nağd, ₼": "Sayılan nakit, ₼",
    "Fərq varsa izah": "Fark varsa açıklama",
    "Bank cəmlərini (POS və köçürmə) gün sonu bank çıxarışı ilə tutuşdurun.": "Banka toplamlarını (POS ve havale) gün sonunda banka ekstresiyle karşılaştırın.",
    "Məbləğ, ₼": "Tutar, ₼",
    "Məxarici təsdiqlə": "Çıkışı onayla",
    "{0} ₼ kassadan çıxarılır: {1}": "Kasadan {0} ₼ çıkarılıyor: {1}",
    "{0} kassadan məxaric istəyir: {1} ₼ ({2})": "{0} kasadan {1} ₼ çıkış istiyor ({2})",
    "Qeydə alındı": "Kaydedildi",
    "Açılış": "Açılış",
    "Bağlanış": "Kapanış",
    "Satış": "Satış",
    "Köçürmə": "Havale",
    "Gözlənilən nağd": "Beklenen nakit",
    "Sayılmış nağd": "Sayılan nakit",
    "Fərq": "Fark",
    "İzah": "Açıklama",
    "Z HESABATI": "Z RAPORU",
    "Yekun ₼": "Toplam ₼",
    "Hələ satış yoxdur": "Henüz satış yok",
    "Dublikat çek": "Fiş kopyası",
    "Çek № {0} \"DUBLİKAT\" qeydi ilə çap olunur.": "Fiş No {0} \"KOPYA\" işaretiyle yazdırılıyor.",
    "Dublikat": "Kopya",
    "Rollar və icazələr": "Roller ve izinler",
    "Hansı rolun hansı əməliyyata icazəsi olduğunu yalnız Admin dəyişir. Hər dəyişiklik audit jurnalına yazılır.": "Hangi rolün hangi işleme izni olduğunu yalnızca Admin değiştirir. Her değişiklik denetim günlüğüne yazılır.",
    "İcazə": "İzin",
    "İcazələr yadda saxlanıldı": "İzinler kaydedildi",
    "Mağaza adı": "Mağaza adı",
    "Ünvan": "Adres",
    "Kassa adı": "Kasa adı",
    "Sinxron açarı (SYNC_TOKEN)": "Senkron anahtarı (SYNC_TOKEN)",
    "Dəyişmək üçün yazın": "Değiştirmek için yazın",
    "Saxlanılıb · dəyişmək üçün yazın": "Kaydedildi · değiştirmek için yazın",
    "server qoşulub": "sunucu bağlı",
    "server qoşulmayıb (yalnız bu cihaz)": "sunucu bağlı değil (yalnızca bu cihaz)",
    "· göndərilməmiş: {0}": "· gönderilmemiş: {0}",
    "· son sinxron: {0}": "· son senkron: {0}",
    "Son xəta: {0}": "Son hata: {0}",
    "Sinxron alınmadı: {0}": "Senkron başarısız: {0}",
    "Ünvan yoxdur və ya oflayn": "Adres yok veya çevrimdışı",
    "{0} qeyd göndərildi, {1} qeyd alındı": "{0} kayıt gönderildi, {1} kayıt alındı",
    "Mağaza və server": "Mağaza ve sunucu",
    "Ünvan boşdursa, sistem yalnız bu kompyuterdə işləyir. Hər yeni brauzer/cihaz bir dəfə qoşulmalıdır (giriş ekranında \"Bu cihazı serverə qoş\").": "Adres boşsa sistem yalnızca bu bilgisayarda çalışır. Her yeni tarayıcı/cihaz bir kez bağlanmalıdır (giriş ekranında \"Bu cihazı sunucuya bağla\").",
    "Bağlantını yoxla": "Bağlantıyı kontrol et",
    "İndi sinxronlaşdır": "Şimdi senkronla",
    "{0} üçün müvəqqəti PIN bir dəfə göstərilir. İndi ötürün: ilk girişdə özünün yeni PIN-ini seçəcək.": "{0} için geçici PIN bir kez gösterilir. Şimdi iletin: ilk girişte kendi yeni PIN'ini seçecek.",
    "PIN dəyişməlidir": "PIN değiştirilmeli",
    "PIN-i sıfırla": "PIN'i sıfırla",
    "Məs. Elvin Babayev": "Örn. Elvin Babayev",
    "Yeni istifadəçi": "Yeni kullanıcı",
    "Ad və soyad": "Ad ve soyad",
    "Rol": "Rol",
    "Müvəqqəti PIN yaradılacaq; istifadəçi ilk girişdə öz PIN-ini seçir.": "Geçici PIN oluşturulacak; kullanıcı ilk girişte kendi PIN'ini seçer.",
    "Yarat": "Oluştur",
    "İstifadəçi yaradıldı": "Kullanıcı oluşturuldu",
    "Redaktə — {0}": "Düzenle — {0}",
    "Öz rolunuzu dəyişə bilməzsiniz.": "Kendi rolünüzü değiştiremezsiniz.",
    "Rol dəyişəndə istifadəçinin açıq cihazında menyu və icazələr bir neçə saniyəyə yenilənir.": "Rol değişince kullanıcının açık cihazında menü ve izinler birkaç saniyede güncellenir.",
    "Dəyişiklik yoxdur": "Değişiklik yok",
    "İstifadəçi artıq daxil ola bilməyəcək, açıq cihazlarda isə bir neçə saniyəyə çıxış edəcək. Keçmiş çeklər və hesabatlar saxlanılır.": "Kullanıcı artık giriş yapamaz, açık cihazlarda birkaç saniye içinde çıkış yapılır. Geçmiş fişler ve raporlar saklanır.",
    "İstifadəçi yenidən daxil ola biləcək (PIN dəyişməyibsə köhnə PIN ilə).": "Kullanıcı yeniden giriş yapabilir (PIN değişmediyse eski PIN ile).",
    "PIN-i sıfırla — {0}": "PIN'i sıfırla — {0}",
    "Müvəqqəti PIN yaradılacaq. İstifadəçi ilk girişdə özünün yeni PIN-ini seçəcək. Köhnə PIN dərhal etibarsız olur.": "Geçici PIN oluşturulacak. Kullanıcı ilk girişte yeni PIN'ini seçecek. Eski PIN hemen geçersiz olur.",
    "Sıfırla": "Sıfırla",
    "Müvəqqəti PIN": "Geçici PIN",
    "İstifadəçilər": "Kullanıcılar",
    "+ Yeni istifadəçi": "+ Yeni kullanıcı",
    "Hesabınız söndürülüb. Yenidən daxil olun": "Hesabınız devre dışı bırakıldı. Yeniden giriş yapın",
    "Bu əməliyyata icazəniz yoxdur: {0}": "Bu işlem için izniniz yok: {0}",
    "Nömrə ehtiyatı bitib. İnternetə qoşulun və bir neçə saniyə gözləyin": "Numara rezervi bitti. İnternete bağlanın ve birkaç saniye bekleyin",
    "İstifadəçi tapılmadı": "Kullanıcı bulunamadı",
    "Çox səhv cəhd. {0} dəqiqə gözləyin": "Çok fazla hatalı deneme. {0} dakika bekleyin",
    "PIN səhvdir": "PIN hatalı",
    "PIN 4–8 rəqəm olmalıdır": "PIN 4–8 haneli olmalıdır",
    "Yeni PIN köhnə PIN ilə eyni ola bilməz": "Yeni PIN eskisiyle aynı olamaz",
    "Çox sadə PIN seçməyin": "Çok basit bir PIN seçmeyin",
    "Köhnə PIN səhvdir": "Eski PIN hatalı",
    "Ad ən azı 2 simvol olmalıdır": "Ad en az 2 karakter olmalıdır",
    "Ad 40 simvoldan uzun ola bilməz": "Ad 40 karakterden uzun olamaz",
    "Bu adda istifadəçi artıq var": "Bu adda bir kullanıcı zaten var",
    "Rol seçin": "Rol seçin",
    "Rol səhvdir": "Rol hatalı",
    "Öz hesabınızı söndürə bilməzsiniz": "Kendi hesabınızı devre dışı bırakamazsınız",
    "Sistemdə ən azı bir aktiv Admin qalmalıdır": "Sistemde en az bir aktif Admin kalmalıdır",
    "PIN yanlışdır və ya bu şəxsin təsdiq icazəsi yoxdur": "PIN yanlış veya bu kişinin onay izni yok",
    "Məhsulun adı boşdur": "Ürün adı boş",
    "Satış qiyməti 0-dan böyük olmalıdır": "Satış fiyatı 0'dan büyük olmalıdır",
    "İstehsalçı barkodunda boşluq ola bilməz": "Üretici barkodunda boşluk olamaz",
    "Bu, mağaza və ya çek barkodudur, istehsalçı barkodu deyil": "Bu mağaza veya fiş barkodu, üretici barkodu değil",
    "Satış qiymətini yalnız Menecer və Admin təyin edir": "Satış fiyatını yalnızca Yönetici ve Admin belirler",
    "Bu istehsalçı barkodu artıq var: {0}": "Bu üretici barkodu zaten var: {0}",
    "Məhsul tapılmadı": "Ürün bulunamadı",
    "Təchizatçının adı ən azı 2 simvol olmalıdır": "Tedarikçi adı en az 2 karakter olmalıdır",
    "Ad 60 simvoldan uzun ola bilməz": "Ad 60 karakterden uzun olamaz",
    "Bu adda təchizatçı artıq var": "Bu adda bir tedarikçi zaten var",
    "Telefon çox uzundur": "Telefon çok uzun",
    "Qeyd 300 simvoldan uzun ola bilməz": "Not 300 karakterden uzun olamaz",
    "Təchizatçı tapılmadı": "Tedarikçi bulunamadı",
    "Say müsbət tam ədəd olmalıdır": "Adet pozitif bir tam sayı olmalıdır",
    "Təchizatçı tapılmadı və ya söndürülüb": "Tedarikçi bulunamadı veya devre dışı",
    "Silinmiş təchizatçı": "Silinmiş tedarikçi",
    "Təchizatçısız (köhnə qalıq / mənfi satış)": "Tedarikçisiz (eski stok / eksi satış)",
    "Başlanğıc nağdı yazın": "Başlangıç nakdini yazın",
    "Artıq açıq növbə var": "Zaten açık bir vardiya var",
    "Əvvəlki növbədən qalıq {0} ₼ idi. Fərqli məbləğ üçün izah yazın": "Önceki vardiyadan kalan {0} ₼ idi. Farklı tutar için açıklama yazın",
    "Səbəbi yazın": "Nedeni yazın",
    "Kassadan məxaric menecer təsdiqi tələb edir": "Kasadan çıkış yönetici onayı gerektirir",
    "Növbə açıq deyil": "Vardiya açık değil",
    "Kassa fərqi var ({0} ₼). İzah yazın": "Kasa farkı var ({0} ₼). Açıklama yazın",
    "Açıq növbə yoxdur": "Açık vardiya yok",
    "Sinxronlaşmamış {0} qeyd var. İnternet qayıdana qədər növbə bağlanmır (FR-104)": "Senkronlanmamış {0} kayıt var. İnternet gelene kadar vardiya kapatılamaz (FR-104)",
    "Endirim menecer tərəfindən təsdiqlənməyib": "İndirim yönetici tarafından onaylanmadı",
    "Satış üçün növbəni açın": "Satış için vardiyayı açın",
    "Məhsul satışda deyil": "Ürün satışta değil",
    "Say səhvdir: {0}": "Adet hatalı: {0}",
    "\"{0}\" qalığı yoxdur və artıq {1} mənfi çekdə satılıb. Mal qəbulu daxil edin": "\"{0}\" stokta yok ve zaten {1} eksi stoklu fişte satıldı. Mal kabulü girin",
    "Çekin qaytarma müddəti bitib ({0} gün keçib, limit {1} gün)": "Fişin iade süresi doldu ({0} gün geçti, sınır {1} gün)",
    "Sətir tapılmadı": "Satır bulunamadı",
    "\"{0}\": say tam müsbət ədəd olmalıdır": "\"{0}\": adet pozitif bir tam sayı olmalıdır",
    "Qaytarma menecer təsdiqi tələb edir": "İade yönetici onayı gerektirir",
    "Qaytarma üçün növbəni açın": "İade için vardiyayı açın",
    "\"{0}\" üzrə ən çox {1} ədəd qaytarmaq olar": "\"{0}\": en fazla {1} adet iade edilebilir",
    "Qaytarılacaq məhsul seçin": "İade edilecek ürünü seçin",
    "Admin icazə idarəsini özündən götürə bilməz": "Admin, izin yönetimini kendisinden alamaz",
    "Qərar səhvdir": "Karar hatalı",
    "Sorğu tapılmadı": "İstek bulunamadı",
    "Öz sorğunuzu təsdiqləyə bilməzsiniz": "Kendi isteğinizi onaylayamazsınız",
    "Sorğuya artıq cavab verilib": "İsteğe zaten yanıt verilmiş",
    "Sorğunun vaxtı bitib": "İsteğin süresi dolmuş",
    "Ünvan boşdur": "Adres boş",
    "Bu /dev ünvanıdır, o yalnız sizin brauzerinizdə işləyir. Deploy → Manage deployments bölməsindən /exec ilə bitən ünvanı götürün": "Bu bir /dev adresidir, yalnızca sizin tarayıcınızda çalışır. Deploy → Manage deployments bölümünden /exec ile biten adresi alın",
    "Bu Apps Script redaktorunun linkidir. Deploy → Manage deployments → Web app URL lazımdır": "Bu Apps Script düzenleyicisinin bağlantısıdır. Deploy → Manage deployments → Web app URL gerekir",
    "Ünvan https://script.google.com/macros/s/…/exec formasında olmalıdır": "Adres https://script.google.com/macros/s/…/exec biçiminde olmalıdır",
    "{0}. İnterneti yoxlayın; Apps Script bəzən yavaş cavab verir, sinxron özü təkrar cəhd edəcək": "{0}. İnterneti kontrol edin; Apps Script bazen yavaş yanıt verir, senkron kendisi yeniden deneyecek",
    "Server cavab vermədi. Ən çox səbəb: Deploy-da \"Who has access\" = \"Anyone\" deyil (yalnız Google hesabına girmiş brauzerdə işləyir, digər brauzerdə yox). Yoxlama: ünvanı gizli pəncərədə açın, {\"ok\":true} görünməlidir. Kodu dəyişəndən sonra \"New version\" deploy etmək də lazımdır": "Sunucu yanıt vermedi. En sık neden: Deploy'da \"Who has access\" = \"Anyone\" değil (yalnızca Google hesabına girmiş tarayıcıda çalışır, diğerlerinde çalışmaz). Kontrol: adresi gizli pencerede açın, {\"ok\":true} görünmeli. Kodu değiştirdikten sonra \"New version\" deploy etmek de gerekir",
    "Server JSON əvəzinə səhifə qaytardı (çox güman Google giriş səhifəsi və ya Apps Script limiti). Deploy-da \"Who has access\" = \"Anyone\" olmalıdır": "Sunucu JSON yerine bir sayfa döndürdü (büyük olasılıkla Google giriş sayfası veya Apps Script sınırı). Deploy'da \"Who has access\" = \"Anyone\" olmalıdır",
    "Server {0} san ərzində cavab vermədi": "Sunucu {0} sn içinde yanıt vermedi",
    "Sorğu dayandırıldı": "İstek durduruldu",
    "Server {0}": "Sunucu {0}",
    "Açar uyğun gəlmir: tətbiqdəki açar Script properties-dəki SYNC_TOKEN ilə eyni olmalıdır": "Anahtar uyuşmuyor: uygulamadaki anahtar Script properties'teki SYNC_TOKEN ile aynı olmalıdır",
    "Server xətası": "Sunucu hatası",
    "Cavab gəldi, amma bu, mağaza skripti deyil": "Yanıt geldi ama bu mağaza betiği değil",
    "Skriptdə SYNC_TOKEN təyin olunmayıb (Project Settings → Script properties)": "Betikte SYNC_TOKEN tanımlı değil (Project Settings → Script properties)",
    "Skriptin köhnə versiyası işləyir. Yeni Code.gs-i yapışdırın və Deploy → Manage deployments → Edit → New version seçin": "Betiğin eski sürümü çalışıyor. Yeni Code.gs'i yapıştırın ve Deploy → Manage deployments → Edit → New version seçin",
    "Cədvəllərdə çatışmayan vərəqlər: {0}. setup() funksiyasını işə salın": "Tablolarda eksik sayfalar var: {0}. setup() fonksiyonunu çalıştırın",
    "Bağlantı işləyir{0}": "Bağlantı çalışıyor{0}",
    ". Diqqət: skript köhnədir (v{0}). {1}{2}telefona bildiriş üçün yeni Code.gs-i yapışdırın, setup() işlədin və \"New version\" deploy edin (tətbiq bu olmadan da işləyir, məlumat Events vərəqində saxlanılır)": ". Dikkat: betik eski (v{0}). {1}{2}telefona bildirim için yeni Code.gs'i yapıştırın, setup() çalıştırın ve \"New version\" deploy edin (uygulama bunsuz da çalışır, veriler Events sayfasında saklanır)",
    "Sürətli sinxron və keş düzəlişi,": "hızlı senkron ve önbellek düzeltmesi,",
    "təchizatçı/partiya cədvəllərinin Sheets-ə yazılması,": "tedarikçi/parti tablolarının Sheets'e yazılması,",
    "Server qoşulmayıb": "Sunucu bağlı değil",
    "Açarı (SYNC_TOKEN) yazın": "Anahtarı (SYNC_TOKEN) yazın",
    "Ləğv et": "İptal et",
    "Menecer PIN-ini yazın və ya sorğu göndərin: menecer öz cihazında təsdiqləyəcək.": "Yönetici PIN'ini yazın veya istek gönderin: yönetici kendi cihazında onaylayacak.",
    "Menecer PIN-ini yazın.": "Yönetici PIN'ini yazın.",
    "Menecer PIN-i": "Yönetici PIN'i",
    "Menecer təsdiqlədi": "Yönetici onayladı",
    "Menecer sorğunu rədd etdi": "Yönetici isteği reddetti",
    "Sorğunun vaxtı bitdi": "İsteğin süresi doldu",
    "Menecerə sorğu göndər": "Yöneticiye istek gönder",
    "Sorğu üçün internet lazımdır. Menecer PIN-i ilə təsdiqləyin": "İstek için internet gerekir. Yönetici PIN'i ile onaylayın",
    "Sorğu menecerə göndərildi, cavab gözlənilir: {0}": "İstek yöneticiye gönderildi, yanıt bekleniyor: {0}",
    "Sorğu ləğv edildi": "İstek iptal edildi",
    "Sorğu menecerə göndərildi": "İstek yöneticiye gönderildi",
    "Qaytarılan@@change": "Para üstü",
    "JSON səhvdir": "Geçersiz JSON",
    "Naməlum əməliyyat": "Bilinmeyen işlem",
    "Naməlum açar": "Bilinmeyen anahtar",
    "Server məşğuldur, sonra təkrar olunacaq": "Sunucu meşgul, daha sonra tekrar denenecek",
    "Bildiriş ünvanı tanınmır": "Bildirim adresi tanınmıyor",
    "Bu cihaz bildiriş üçün qeydiyyatdan keçməyib": "Bu cihaz bildirimler için kayıtlı değil",
    "Mal qəbulu sorğusu göndərmək (menecer təsdiqləyir)": "Mal kabul isteği göndermek (yönetici onaylar)",
    "Qəbul təsdiqləndi, qalıq artırıldı: {0} ədəd": "Kabul onaylandı, stok artırıldı: {0} adet",
    "Hazırkı qalıq: {0}": "Mevcut stok: {0}",
    "Təsdiqlə və qəbul et": "Onayla ve kabul et",
    "Mal gəldi: menecerə təsdiq sorğusu göndər": "Mal geldi: yöneticiye onay isteği gönder",
    "Mal gəldi": "Mal geldi",
    "Gözləyir": "Bekliyor",
    "Ləğv edildi": "İptal edildi",
    "Vaxtı bitib": "Süresi doldu",
    "Mal qəbulu sorğularım": "Mal kabul isteklerim",
    "Qalıq menecer təsdiqləyəndən sonra artır.": "Stok, yönetici onayladıktan sonra artar.",
    "Vaxt": "Zaman",
    "— bilmirəm / menecer seçəcək —": "— bilmiyorum / yönetici seçecek —",
    "Mal gəldi — {0}": "Mal geldi — {0}",
    "Gələn malın sayını yazın. Sorğu menecerə gedir; qalıq menecer təsdiqləyəndən sonra artacaq (hazırkı qalıq: {0}).": "Gelen malın adedini yazın. İstek yöneticiye gider; stok onaydan sonra artar (mevcut stok: {0}).",
    "Server qoşulmayıb: sorğu menecerin cihazına çata bilməz. Mal qəbulunu menecer özü etməlidir": "Sunucu bağlı değil: istek yöneticinin cihazına ulaşamaz. Mal kabulünü yönetici kendisi yapmalıdır.",
    "Say {0}-dən çox ola bilməz": "Adet {0} değerinden fazla olamaz",
    "Qeyd 200 simvoldan uzun ola bilməz": "Not 200 karakterden uzun olamaz",
    "Bu məhsul üçün sorğu artıq menecerin cavabını gözləyir. Dəyişmək istəyirsinizsə əvvəl onu ləğv edin": "Bu ürün için istek zaten yöneticinin yanıtını bekliyor. Değiştirmek istiyorsanız önce iptal edin.",
    "{0} mal qəbulu istəyir: «{1}», {2} ədəd": "{0} mal kabulü istiyor: \"{1}\", {2} adet",
    "Saat səhvdir": "Saat yanlış",
    "Bu cihazın saatı serverdən {0} dəq. fərqlənir. Çek tarixləri avtomatik düzəldilir, amma cihazın saatını \"avtomatik\" rejimə keçirin": "Bu cihazın saati sunucudan {0} dk farklı. Fiş tarihleri otomatik düzeltilir, ancak cihazı otomatik saate geçirin",
    "Bir çekdə ən çox {0} sətir ola bilər. Çeki iki hissəyə bölün": "Bir fişte en fazla {0} satır olabilir. Fişi ikiye bölün"
  });
})(typeof window !== 'undefined' ? window : globalThis);
