/* Rus dili tərcümələri (açar = Azərbaycanca mənbə mətni). Yeni mətn əlavə edəndə: node tools/i18n-scan.js --missing və npm test. */
(function (root) {
  'use strict';
  root.I18n.add('ru', {
    "Kassa": "Касса",
    "Qaytarma": "Возврат",
    "Məhsullar": "Товары",
    "Təchizatçılar": "Поставщики",
    "Çeklər": "Чеки",
    "Növbə": "Смена",
    "İcazələr": "Права доступа",
    "Bu rol üçün açıq ekran yoxdur.": "Для этой роли нет доступных экранов.",
    "Onlayn": "Онлайн",
    "Oflayn": "Офлайн",
    "Google Apps Script serverinin orta cavab müddəti. Cihazlar arasında yenilik təxminən bunun 2–3 qatı qədər gecikir": "Среднее время ответа сервера Google Apps Script. Обновления между устройствами приходят примерно в 2–3 раза позже.",
    "Server {0} san": "Сервер {0} с",
    "Tətbiq versiyası. İki cihazda eyni olmalıdır; fərqlidirsə Ctrl+F5 basın": "Версия приложения. На двух устройствах должна совпадать; если отличается, нажмите Ctrl+F5",
    "Serverə göndərilməmiş qeydlər": "Записи, не отправленные на сервер",
    "{0} sinxron gözləyir": "Ожидают синхронизации: {0}",
    "Sinxron xətası": "Ошибка синхронизации",
    "Sorğular ({0})": "Запросы ({0})",
    "Növbə açıq · {0}": "Смена открыта · {0}",
    "Növbə bağlı": "Смена закрыта",
    "Təsdiq sorğusu gələndə telefona/brauzerə bildiriş": "Уведомление на телефон/в браузер при запросе подтверждения",
    "Bildiriş": "Уведомления",
    "Bu cihazın printeri: kağız eni, etiket ölçüsü, test çapı": "Принтер этого устройства: ширина бумаги, размер этикетки, пробная печать",
    "Çap": "Печать",
    "Çıxış": "Выход",
    "Yeni təsdiq sorğusu: {0}": "Новый запрос на подтверждение: {0}",
    "Hesabınız dəyişdirilib və ya söndürülüb. Yenidən daxil olun": "Ваша учётная запись изменена или отключена. Войдите заново",
    "Bölmələr": "Разделы",
    "7BOXS — Kassa": "7BOXS — Касса",
    "Başlatma xətası: {0}": "Ошибка запуска: {0}",
    "Bildiriş yalnız təhlükəsiz (https) ünvanda işləyir": "Уведомления работают только по защищённому адресу (https)",
    "iPhone/iPad-də bildiriş yalnız tətbiq ana ekrana əlavə edilibsə işləyir: Safari → Paylaş → \"Ana ekrana əlavə et\", sonra oradan açın (iOS 16.4 və yuxarı)": "На iPhone/iPad уведомления работают, только если приложение добавлено на главный экран: Safari → Поделиться → «На экран «Домой»», затем откройте оттуда (iOS 16.4 и выше)",
    "Bu brauzer bildirişi dəstəkləmir. Chrome, Edge və ya Firefox-un yeni versiyasından istifadə edin": "Этот браузер не поддерживает уведомления. Используйте свежую версию Chrome, Edge или Firefox",
    "Xidmət işçisi (service worker) işləmir. Səhifəni yeniləyin (Ctrl+F5); tətbiq https ünvanından açılmalıdır": "Сервис-воркер (service worker) не работает. Обновите страницу (Ctrl+F5); приложение должно открываться по адресу https",
    "Server skripti köhnədir: Code.gs-in v6 versiyasını yapışdırın, setup() işlədin və \"New version\" deploy edin": "Скрипт сервера устарел: вставьте версию Code.gs v6, запустите setup() и сделайте deploy «New version»",
    "Apps Script-də V8 runtime aktiv deyil (BigInt yoxdur): Project Settings → \"Chrome V8 runtime\" seçin, sonra New version deploy edin. Sinxron təsirlənmir, yalnız bildiriş işləmir": "В Apps Script не включён V8 runtime (нет BigInt): Project Settings → выберите «Chrome V8 runtime», затем сделайте deploy New version. Синхронизация не затронута, не работают только уведомления",
    "Apps Script-ə xarici sorğu icazəsi verilməyib: redaktorda setup() işlədin, \"Connect to an external service\" icazəsini təsdiqləyin və yenidən \"New version\" deploy edin": "Apps Script не получил разрешения на внешние запросы: запустите setup() в редакторе, подтвердите разрешение «Connect to an external service» и снова сделайте deploy «New version»",
    "Əvvəl serveri qoşun (İcazələr → Mağaza və server)": "Сначала подключите сервер (Права доступа → Магазин и сервер)",
    "Daxil olun": "Войдите в систему",
    "Bildiriş bloklanıb. Brauzerin ünvan sətrindəki qıfıl işarəsi → Bildirişlər → \"İcazə ver\", sonra yenidən basın": "Уведомления заблокированы. Значок замка в адресной строке браузера → Уведомления → «Разрешить», затем нажмите снова",
    "Bildiriş icazəsi verilmədi": "Разрешение на уведомления не выдано",
    "Bu rolun təsdiq sorğusu almaq icazəsi yoxdur": "У этой роли нет права получать запросы на подтверждение",
    "Təsdiq sorğusu": "Запрос на подтверждение",
    "Kassadan menecer təsdiqi gözlənilir": "Кассир ждёт подтверждения менеджера",
    "7BOXS — test": "7BOXS — тест",
    "Bildirişlər bu cihazda işləyir.": "Уведомления на этом устройстве работают.",
    "Bu cihaz push üçün qoşulmayıb. \"Aktiv et\" düyməsini basın": "Это устройство не подключено к push. Нажмите «Включить»",
    "Kassir təsdiq sorğusu göndərəndə (sətir silmə, endirim, qaytarma) bu cihaza bildiriş gəlsin. Hər menecer cihazında bir dəfə aktiv edilir.": "Когда кассир отправляет запрос на подтверждение (удаление строки, скидка, возврат), на это устройство придёт уведомление. Включается один раз на каждом устройстве менеджера.",
    "Brauzer icazəsi verilib": "Разрешение браузера выдано",
    "Brauzer bildirişi bloklayıb (ünvan sətrindəki qıfıldan açın)": "Браузер заблокировал уведомления (разблокируйте через значок замка в адресной строке)",
    "Brauzer icazəsi hələ verilməyib": "Разрешение браузера ещё не выдано",
    "Bu cihaz bildirişə qoşulub": "Устройство подписано на уведомления",
    "Bu cihaz bildirişə qoşulmayıb": "Устройство не подписано на уведомления",
    "Bu rolun təsdiq sorğusu almaq icazəsi yoxdur (Menecer və ya Admin daxil olmalıdır)": "У этой роли нет права получать запросы на подтверждение (нужен вход как Менеджер или Админ)",
    "Test bildirişi göndər": "Отправить тестовое уведомление",
    "Söndür": "Отключить",
    "Bildiriş aktiv edildi": "Уведомления включены",
    "Aktiv et": "Включить",
    "Göndərilir…": "Отправляется…",
    "Bu cihazda bildiriş göstərildi (ikon və səs yoxlanılır)": "На этом устройстве показано уведомление (проверьте значок и звук)",
    "Bu cihazda bildiriş göstərilmədi: {0}": "На этом устройстве уведомление не показано: {0}",
    "naməlum səbəb": "неизвестная причина",
    "Server push xidmətinə göndərdi (cavab {0}). 5–15 saniyəyə \"Təsdiq sorğusu\" bildirişi gəlməlidir; tətbiqi başqa tabə keçirin": "Сервер отправил в push-службу (ответ {0}). Уведомление «Запрос на подтверждение» должно прийти за 5–15 секунд; переключитесь на другую вкладку",
    "Push xidməti rədd etdi (cavab {0}): {1}. Söndürüb yenidən aktiv edin": "Push-служба отклонила (ответ {0}): {1}. Отключите и включите заново",
    "Bildirişlər": "Уведомления",
    "Bağla": "Закрыть",
    "Yarımçıq çek bərpa olundu ({0} sətir)": "Незавершённый чек восстановлен (строк: {0})",
    "\"{0}\" qalığı yoxdur və limit ({1} mənfi çek) dolub. Satmaq olmaz — mal qəbulu lazımdır (qəbulu menecer edir).": "Остатка «{0}» нет, и лимит ({1} чека с отрицательным остатком) исчерпан. Продать нельзя — нужно оприходовать товар (приход делает менеджер).",
    "Diqqət: \"{0}\" qalığı {1}. Mənfi qalıqla satış {2}/{3} çek.": "Внимание: остаток «{0}» — {1}. Продажа с отрицательным остатком {2}/{3} чеков.",
    "{0} əlavə olundu": "{0} добавлен",
    "Bu istehsalçı barkodudur. Məhsulun üzərindəki mağaza barkodunu oxudun ({0}).": "Это штрихкод производителя. Отсканируйте штрихкод магазина на товаре ({0}).",
    "Bu çek barkodudur. Qaytarma üçün \"Qaytarma\" bölməsinə keçin.": "Это штрихкод чека. Для возврата перейдите в раздел «Возврат».",
    "\"{0}\" satışdan çıxarılıb.": "«{0}» снят с продажи.",
    "Barkod tapılmadı: {0}": "Штрихкод не найден: {0}",
    "Sayı 1-dən azaltmaq olmaz. Sətri silmək üçün zibil ikonuna basın (menecer təsdiqi lazımdır).": "Количество нельзя уменьшить меньше 1. Чтобы удалить строку, нажмите на значок корзины (нужно подтверждение менеджера).",
    "Bu sətir üçün sorğu artıq göndərilib, menecer cavabı gözlənilir": "Запрос по этой строке уже отправлен, ожидается ответ менеджера",
    "Sətri çekdən sil": "Удалить строку из чека",
    "{0} çekdən çıxarılır.": "{0} удаляется из чека.",
    "{0} sətir silmək istəyir: {1}": "{0} хочет удалить строку: {1}",
    "Təsdiq olunan {0} ədəd silindi, sətirdə {1} qaldı ({2} təsdiqlədi)": "Подтверждённое количество {0} удалено, в строке осталось {1} ({2} подтвердил)",
    "Sətir silindi ({0} təsdiqlədi)": "Строка удалена ({0} подтвердил)",
    "Çekin ləğvi üçün sorğu artıq göndərilib": "Запрос на отмену чека уже отправлен",
    "Çeki ləğv et": "Отменить чек",
    "Bütün çek ({0} ₼) ləğv olunur.": "Весь чек ({0} ₼) отменяется.",
    "{0} çeki ləğv etmək istəyir: {1} ₼": "{0} хочет отменить чек: {1} ₼",
    "Çek arada dəyişdi, təsdiq olunmuş ləğv tətbiq edilmədi": "Чек тем временем изменился, подтверждённая отмена не применена",
    "Endirim sorğusu": "Запрос скидки",
    "Endirim, % (ən çox {0}%)": "Скидка, % (не более {0}%)",
    "Endirimi götür": "Убрать скидку",
    "İmtina": "Отмена",
    "Menecerə göndər": "Отправить менеджеру",
    "{0}% endirim: {1} → {2} ₼": "Скидка {0}%: {1} → {2} ₼",
    "Endirimi təsdiqlə": "Подтвердить скидку",
    "{0} endirim istəyir: {1}% endirim: {2} → {3} ₼": "{0} просит скидку: {1}%: {2} → {3} ₼",
    "Çek arada dəyişdi, təsdiqlənmiş endirim tətbiq edilmədi. Yenidən sorğu göndərin": "Чек тем временем изменился, подтверждённая скидка не применена. Отправьте запрос заново",
    "{0}% endirim təsdiqləndi ({1})": "Скидка {0}% подтверждена ({1})",
    "Endirim təsdiqlənmədi": "Скидка не подтверждена",
    "Çek № {0} tamamlandı{1}{2}": "Чек № {0} завершён{1}{2}",
    "· qaytarılacaq {0} ₼": "сдача {0} ₼",
    "· ÇEK ÇAP OLUNMADI ({0}): Çeklər bölməsindən təkrar çap edin": "ЧЕК НЕ НАПЕЧАТАН ({0}): повторно напечатайте в разделе «Чеки»",
    "məs. say səhv idi, sayım nəticəsi": "напр. ошибся при пересчёте, результат подсчёта",
    "Fərqin izahı (əvvəlki növbənin qalığından fərqlidir)": "Объяснение разницы (отличается от остатка предыдущей смены)",
    "Məbləğ səhvdir": "Неверная сумма",
    "Yoxlanılır…": "Проверка…",
    "Növbə açıldı": "Смена открыта",
    "Növbəni aç": "Открыть смену",
    "Növbə bağlıdır": "Смена закрыта",
    "Satışa başlamaq üçün kassadakı başlanğıc nağdı sayıb yazın.": "Чтобы начать продажи, пересчитайте и введите начальную сумму наличных в кассе.",
    "Əvvəlki növbədən kassada qalan nağd: {0} ₼ ({1}). Növbə bu məbləğlə başlayır; kassanı sayıb fərqli çıxsa dəyişin və izah yazın.": "Наличные, оставшиеся в кассе с предыдущей смены: {0} ₼ ({1}). Смена начнётся с этой суммы; если при пересчёте сумма отличается, измените её и напишите объяснение.",
    "Başlanğıc nağd, ₼": "Начальные наличные, ₼",
    "Barkodu oxudun — məhsul burada görünəcək": "Отсканируйте штрихкод — товар появится здесь",
    "Qalıq yoxdur, limit dolub — satılmaz": "Остатка нет, лимит исчерпан — не продаётся",
    "Qalıq {0} · mənfi qalıqla satış {1}/{2}": "Остаток {0} · продажа с отрицательным остатком {1}/{2}",
    "Azalt": "Уменьшить",
    "Sətri silmək üçün zibil ikonu (menecer təsdiqi)": "Значок корзины для удаления строки (подтверждение менеджера)",
    "Sayı azalt": "Уменьшить количество",
    "Artır": "Увеличить",
    "{0} ədəd": "{0} шт.",
    "Menecer cavabı gözlənilir": "Ожидается ответ менеджера",
    "Sətri sil (menecer təsdiqi lazımdır)": "Удалить строку (нужно подтверждение менеджера)",
    "Sətri sil: {0}": "Удалить строку: {0}",
    "Nağd ödəniş": "Оплата наличными",
    "Bank ödənişi": "Банковский платёж",
    "Qarışıq ödəniş": "Смешанная оплата",
    "Bank növü": "Тип банковского платежа",
    "POS kart": "Карта (POS)",
    "Karta köçürmə": "Перевод на карту",
    "Bank hissəsi, ₼": "Часть банком, ₼",
    "Müştəridən alınan nağd, ₼ (boş qoysanız — dəqiq nağd hissə)": "Получено от покупателя наличными, ₼ (если пусто — точная наличная часть)",
    "Müştəridən alınan nağd, ₼": "Получено от покупателя наличными, ₼",
    "Dəqiq məbləğ": "Точная сумма",
    "Terminalda / bank tətbiqində {0} ₼ ödənişin keçdiyini yoxlayın, sonra təsdiqləyin.": "Убедитесь на терминале / в банковском приложении, что платёж {0} ₼ прошёл, затем подтвердите.",
    "Yazılır…": "Сохраняется…",
    "Təsdiqlə və çek çap et (Enter)": "Подтвердить и напечатать чек (Enter)",
    "Nağd hissə: {0} ₼": "Наличная часть: {0} ₼",
    "Qaytarılacaq": "Сдача",
    "Məhsul": "Товар",
    "Mağaza barkodu": "Штрихкод магазина",
    "Say": "Кол-во",
    "Qiymət": "Цена",
    "Cəm": "Сумма",
    "Sil": "Удалить",
    "Endirim (F4)": "Скидка (F4)",
    "Ləğv (Esc)": "Отмена (Esc)",
    "Çek": "Чек",
    "↑/↓ sətir seçimi · + / − say · Del və ya zibil ikonu: sətri silmək (menecer təsdiqi: PIN və ya sorğu).": "↑/↓ выбор строки · + / − количество · Del или значок корзины: удалить строку (подтверждение менеджера: PIN или запрос).",
    "Ödəniş": "Оплата",
    "Ara cəm": "Промежуточный итог",
    "Endirim": "Скидка",
    "Yekun": "Итого",
    "Nağd": "Наличные",
    "Bank": "Банк",
    "Qarışıq": "Смешанная",
    "Nağd alınan": "Получено наличными",
    "Qaytarılan": "Возвращено",
    "DUBLİKAT": "ДУБЛИКАТ",
    "VÖEN": "VÖEN",
    "Çek №": "Чек №",
    "Tarix": "Дата",
    "Kassir": "Кассир",
    "Endirim {0}%": "Скидка {0}%",
    "YEKUN": "ИТОГО",
    "Qaytarma {0} gün ərzində, çeklə": "Возврат в течение {0} дн. по чеку",
    "Bu çek fiskal çek deyil": "Это не фискальный чек",
    "QAYTARMA ÇEKİ": "ЧЕК ВОЗВРАТА",
    "İlkin çek №": "Исходный чек №",
    "Təsdiqləyən": "Подтвердил",
    "ÇAP SINAĞI": "ПРОБНАЯ ПЕЧАТЬ",
    "Kağız {0} mm · çap sahəsi {1} mm": "Бумага {0} мм · область печати {1} мм",
    "← bütün çərçivə görünməlidir →": "← рамка должна быть видна целиком →",
    "{0} dpi · zolaq {1} mm": "{0} dpi · полоса {1} мм",
    "80 mm (XP-80, XP-N160 …)": "80 мм (XP-80, XP-N160 …)",
    "58 mm (XP-58 …)": "58 мм (XP-58 …)",
    "203 dpi (adətən)": "203 dpi (обычно)",
    "300 dpi": "300 dpi",
    "Tətbiq kağız ölçüsünü verir (tövsiyə)": "Размер бумаги задаёт приложение (рекомендуется)",
    "Çap sürücüsünün ölçüsü": "Размер из драйвера печати",
    "Digər ölçü…": "Другой размер…",
    "203 dpi (XP-365B, XP-420B …)": "203 dpi (XP-365B, XP-420B …)",
    "Tətbiq etiket ölçüsünü verir (tövsiyə)": "Размер этикетки задаёт приложение (рекомендуется)",
    "En, mm": "Ширина, мм",
    "Hündürlük, mm": "Высота, мм",
    "Etiketdə barkod zolağı: {0} mm ({1} nöqtə), eni {2} mm.{3}": "Полоса штрихкода на этикетке: {0} мм ({1} точек), ширина {2} мм.{3}",
    "Etiket çox dardır: barkod oxunmaya bilər, daha geniş etiket seçin.": "Этикетка слишком узкая: штрихкод может не считываться, выберите шире.",
    "Çap ayarları (bu cihaz üçün)": "Настройки печати (для этого устройства)",
    "Çek printeri (termo)": "Принтер чеков (термо)",
    "Kağız eni": "Ширина бумаги",
    "Çap sıxlığı": "Плотность печати",
    "Kağız ölçüsü": "Размер бумаги",
    "Çekdən sonra boşluq, mm": "Пробел после чека, мм",
    "Çekin dili": "Язык чека",
    "Test çeki çap et": "Напечатать тестовый чек",
    "Etiket printeri": "Принтер этикеток",
    "Etiket ölçüsü": "Размер этикетки",
    "Test etiketi çap et": "Напечатать тестовую этикетку",
    "Çap pəncərəsində: Printer — Xprinter, Miqyas — 100%, Kənar boşluqlar — Yoxdur, Başlıq və sonluq — söndürülü. Test çapında çərçivə tam görünmürsə, kənar boşluğu və ya \"Kağız ölçüsü\" seçimini dəyişin.": "В окне печати: Принтер — Xprinter, Масштаб — 100%, Поля — Нет, Верхний и нижний колонтитулы — выключены. Если рамка на пробной печати видна не полностью, измените поля или параметр «Размер бумаги».",
    "Yadda saxla": "Сохранить",
    "Çap ayarları yadda saxlanıldı": "Настройки печати сохранены",
    "Eyni mağaza barkodu iki məhsulda: \"{0}\" və \"{1}\" ({2})": "Один штрихкод магазина у двух товаров: «{0}» и «{1}» ({2})",
    "Çek № {0} iki cihazda verilib (hər ikisi saxlanıldı)": "Чек № {0} выдан на двух устройствах (сохранены оба)",
    "Hadisə tətbiq olunmadı ({0}): {1}": "Событие не применено ({0}): {1}",
    "Etibarsız hadisə rədd edildi ({0})": "Недопустимое событие отклонено ({0})",
    "Bu səhifə çərçivə içində açıla bilməz": "Эту страницу нельзя открыть во фрейме",
    "Satış etmək": "Продавать",
    "Endirimi təsdiqləmək": "Подтверждать скидки",
    "Çekdən sətir silmək": "Удалять строки из чека",
    "Qaytarma sorğusu": "Запрос возврата",
    "Qaytarmanı təsdiqləmək": "Подтверждать возвраты",
    "Növbə açıb bağlamaq": "Открывать и закрывать смену",
    "Məhsullara baxmaq": "Просматривать товары",
    "Məhsul yaratmaq və dəyişmək": "Создавать и изменять товары",
    "Mal qəbul etmək (qalığı artırmaq)": "Оприходовать товар (увеличивать остаток)",
    "Satış qiymətini təyin etmək": "Назначать цену продажи",
    "Alış qiymətini görmək": "Видеть закупочную цену",
    "Etiket çap etmək": "Печатать этикетки",
    "Hesabatlara baxmaq": "Просматривать отчёты",
    "Təchizatçılara və təchizatçı hesabatına baxmaq": "Просматривать поставщиков и отчёт по поставщикам",
    "Təchizatçı əlavə etmək və dəyişmək": "Добавлять и изменять поставщиков",
    "İstifadəçiləri idarə etmək": "Управлять пользователями",
    "İcazə matrisini dəyişmək": "Изменять матрицу прав",
    "Admin": "Админ",
    "Menecer": "Менеджер",
    "Mühasib": "Бухгалтер",
    "Endirim faizi 0-dan böyük olmalıdır": "Процент скидки должен быть больше 0",
    "Endirim {0}%-dən çox ola bilməz": "Скидка не может быть больше {0}%",
    "Çek boşdur": "Чек пуст",
    "Alınan məbləği yazın": "Введите полученную сумму",
    "Alınan məbləğ yekundan azdır": "Полученная сумма меньше итога",
    "POS kart və ya köçürmə seçin": "Выберите «Карта (POS)» или «Перевод»",
    "Bank hissəsinin növünü seçin": "Выберите тип банковской части",
    "Bank hissəsini yazın": "Введите банковскую часть",
    "Bank hissəsi yekundan az olmalıdır, əks halda \"Bank\" seçin": "Банковская часть должна быть меньше итога, иначе выберите «Банк»",
    "Nağd alınan məbləğ nağd hissədən azdır": "Полученные наличные меньше наличной части",
    "Ödəniş üsulu seçilməyib": "Способ оплаты не выбран",
    "İstifadəçi": "Пользователь",
    "Daxil ol": "Войти",
    "Mağaza idarəetmə sistemi": "Система управления магазином",
    "PIN": "PIN",
    "İstifadəçini seçin": "Выберите пользователя",
    "Server qoşulub · istifadəçilər və məlumat avtomatik yenilənir": "Сервер подключён · пользователи и данные обновляются автоматически",
    "Bu cihazı serverə qoş": "Подключить это устройство к серверу",
    "Başqa cihazda artıq işləyirsinizsə, bunu edin: istifadəçilər, məhsullar və çeklər oradan yüklənəcək.": "Если вы уже работаете на другом устройстве, сделайте это: пользователи, товары и чеки загрузятся оттуда.",
    "Ünvanı və açarı (SYNC_TOKEN) yazın. Məlumat serverdən yüklənəcək, bir neçə saniyə çəkə bilər.": "Введите адрес и ключ (SYNC_TOKEN). Данные загрузятся с сервера, это может занять несколько секунд.",
    "Apps Script veb tətbiq ünvanı": "Адрес веб-приложения Apps Script",
    "Sinxron açarı": "Ключ синхронизации",
    "Qoş və yüklə": "Подключить и загрузить",
    "Yoxlanılır və yüklənir…": "Проверка и загрузка…",
    "Qoşuldu · {0} qeyd yükləndi": "Подключено · загружено записей: {0}",
    "Yeni PIN təyin edin": "Задайте новый PIN",
    "İşə başlamazdan əvvəl yalnız sizə məlum olan 4–8 rəqəmli PIN seçin.": "Прежде чем начать работу, выберите PIN из 4–8 цифр, известный только вам.",
    "Hazırkı PIN": "Текущий PIN",
    "Yeni PIN": "Новый PIN",
    "Yeni PIN təkrar": "Повторите новый PIN",
    "Saxla və davam et": "Сохранить и продолжить",
    "Yeni PIN-lər eyni deyil": "Новые PIN не совпадают",
    "PIN dəyişdirildi": "PIN изменён",
    "Təsdiq sorğuları": "Запросы на подтверждение",
    "Gözləyən sorğu yoxdur.": "Нет ожидающих запросов.",
    "Təsdiqləndi": "Подтверждено",
    "Rədd edildi": "Отклонено",
    "Rədd et": "Отклонить",
    "Təsdiqlə": "Подтвердить",
    "Ad, mağaza və ya istehsalçı barkodu": "Название, штрихкод магазина или производителя",
    "Nümunə məhsullar əlavə olundu": "Примеры товаров добавлены",
    "Sınaq üçün nümunə məhsullar əlavə et": "Добавить примеры товаров для пробы",
    "Uyğun məhsul yoxdur": "Подходящих товаров нет",
    "Hələ məhsul yoxdur": "Товаров пока нет",
    "köhnə qalıq": "старый остаток",
    "Aktiv": "Активен",
    "Passiv": "Неактивен",
    "Dəyiş": "Изменить",
    "Qəbul": "Приход",
    "Partiyalar": "Партии",
    "Etiket": "Этикетка",
    "Axtarış": "Поиск",
    "Yeni məhsul": "Новый товар",
    "İstehsalçı barkodu": "Штрихкод производителя",
    "Satış ₼": "Продажа ₼",
    "Orta maya ₼": "Средняя себестоимость ₼",
    "Qalıq": "Остаток",
    "Təchizatçı (qalıq)": "Поставщик (остаток)",
    "Status": "Статус",
    "Ad *": "Название *",
    "Kateqoriya": "Категория",
    "Brend": "Бренд",
    "Yaş qrupu": "Возрастная группа",
    "məs. 3+": "напр. 3+",
    "İstehsalçı barkodu (nəzarət üçün, uzunluq məhdud deyil)": "Штрихкод производителя (для контроля, длина не ограничена)",
    "Satış qiyməti, ₼ *": "Цена продажи, ₼ *",
    "Alış qiyməti, ₼": "Закупочная цена, ₼",
    "Minimum qalıq": "Минимальный остаток",
    "Satış qiymətini yalnız Menecer və Admin təyin edir.": "Цену продажи назначают только Менеджер и Админ.",
    "Mağaza barkodu:": "Штрихкод магазина:",
    "(dəyişmir)": "(не меняется)",
    "Mağaza barkodu yadda saxlayanda avtomatik veriləcək.": "Штрихкод магазина будет присвоен автоматически при сохранении.",
    "Satışda aktivdir": "Активен в продаже",
    "Məhsulu dəyiş": "Изменить товар",
    "Satış qiyməti səhvdir": "Неверная цена продажи",
    "Alış qiyməti səhvdir": "Неверная закупочная цена",
    "Məhsul yaradıldı · {0}": "Товар создан · {0}",
    "Yadda saxlanıldı": "Сохранено",
    "Qaimə №, izah": "№ накладной, пояснение",
    "— təchizatçı seçin —": "— выберите поставщика —",
    "— təchizatçı yoxdur —": "— поставщиков нет —",
    "FIFO: hər satış ən köhnə partiyadan çıxır, hesabatda təchizatçıya görə görünür.": "FIFO: каждая продажа списывается с самой старой партии, в отчёте видно по поставщикам.",
    "Hələ təchizatçı yoxdur. Yeni təchizatçı əlavə edin; təchizatçısız qəbul \"köhnə qalıq\" kimi sayılır.": "Поставщиков пока нет. Добавьте нового поставщика; приход без поставщика считается «старым остатком».",
    "+ Yeni təchizatçı": "+ Новый поставщик",
    "Mal qəbulu — {0}": "Приход товара — {0}",
    "Hazırkı qalıq: {0}. Hər qəbul ayrıca partiyadır (təchizatçı, say, alış qiyməti).": "Текущий остаток: {0}. Каждый приход — отдельная партия (поставщик, количество, закупочная цена).",
    "Təchizatçı": "Поставщик",
    "Alış qiyməti (ədəd), ₼": "Закупочная цена (за шт.), ₼",
    "Qeyd": "Примечание",
    "Qəbul et": "Принять",
    "Təchizatçını seçin": "Выберите поставщика",
    "Qalıq: {0}": "Остаток: {0}",
    "Şirkət və ya şəxs adı": "Название компании или имя",
    "VÖEN, ünvan, şərtlər…": "VÖEN, адрес, условия…",
    "Təchizatçını dəyiş": "Изменить поставщика",
    "Yeni təchizatçı": "Новый поставщик",
    "Telefon": "Телефон",
    "Partiyalar (FIFO) — {0}": "Партии (FIFO) — {0}",
    "Bu məhsul üzrə qəbul yoxdur.": "По этому товару приходов нет.",
    "Qəbul tarixi": "Дата прихода",
    "Alış ₼": "Закупка ₼",
    "Köhnə qalıq": "Старый остаток",
    "Təchizatçısız": "Без поставщика",
    "Satış ən köhnə partiyadan çıxır. \"Qalıq\" sütunu hələ satılmamış hissədir.": "Продажа списывается с самой старой партии. Столбец «Остаток» — ещё не проданная часть.",
    "Etiket {0} × {1} mm · {2} dpi · barkod zolağı {3} mm{4}": "Этикетка {0} × {1} мм · {2} dpi · полоса штрихкода {3} мм{4}",
    "— etiket dardır, barkod oxunmaya bilər": "— этикетка узкая, штрихкод может не считываться",
    "Etiket çapı": "Печать этикеток",
    "Etiket sayı": "Количество этикеток",
    "Çap ayarları": "Настройки печати",
    "Çap et": "Напечатать",
    "Bu ay": "Этот месяц",
    "Bu gün": "Сегодня",
    "Dünən": "Вчера",
    "Keçən ay": "Прошлый месяц",
    "Bütün vaxt": "За всё время",
    "Seçilmiş tarixlər": "Выбранные даты",
    "Hələ təchizatçı yoxdur": "Поставщиков пока нет",
    "Söndürülüb": "Отключён",
    "Redaktə": "Редактировать",
    "Söndürüldü": "Отключено",
    "Aktiv edildi": "Включено",
    "Diqqət: {0} ədəd mal satılandan artıq qaytarılıb (məsələn, iki cihaz eyni çekin eyni sətrini oflayn qaytarıb). Qaytarmalar bölməsində həmin çeki yoxlayın; pul iki dəfə qaytarılmış ola bilər.": "Внимание: {0} шт. возвращено больше, чем продано (например, два устройства оформили возврат одной строки одного чека офлайн). Проверьте этот чек в разделе «Возврат»; деньги могли быть возвращены дважды.",
    "Satılan": "Продано",
    "Xalis ədəd": "Чистое кол-во",
    "Gəlir ₼": "Выручка ₼",
    "Maya (FIFO) ₼": "Себестоимость (FIFO) ₼",
    "Mənfəət ₼": "Прибыль ₼",
    "Qalıq (ədəd)": "Остаток (шт.)",
    "Qalığın dəyəri ₼": "Стоимость остатка ₼",
    "Bu dövrdə məlumat yoxdur": "За этот период данных нет",
    "Cəmi": "Всего",
    "{0} — məhsullar": "{0} — товары",
    "Xalis": "Чисто",
    "Maya ₼": "Себестоимость ₼",
    "Gəlir": "Выручка",
    "Maya (FIFO)": "Себестоимость (FIFO)",
    "Mənfəət": "Прибыль",
    "Ad": "Имя",
    "Vəziyyət": "Состояние",
    "Hansı təchizatçının malından nə qədər satılıb": "Сколько продано товара каждого поставщика",
    "Excel üçün CSV": "CSV для Excel",
    "Dövr": "Период",
    "Başlanğıc": "Начало",
    "Son": "Конец",
    "Satış FIFO ilədir: hər çek ən köhnə partiyadan çıxır. Gəlir endirimdən sonrakı məbləğdir, qaytarmalar çıxılır. \"Təchizatçısız\" — sistemə köçməzdən əvvəlki qalıq və ya qəbuldan əvvəl (mənfi qalıqla) satılan mal. Oflayn cihaz sonra sinxronlaşanda bölgü təchizatçılar arasında düzələ bilər, cəmlər dəyişmir.": "Продажа идёт по FIFO: каждый чек списывается с самой старой партии. Выручка — сумма после скидки, возвраты вычтены. «Без поставщика» — остаток, бывший до перехода на систему, или товар, проданный до прихода (с отрицательным остатком). Когда офлайн-устройство позже синхронизируется, распределение между поставщиками может уточниться, итоги не меняются.",
    "Çek tapılmadı": "Чек не найден",
    "({0}% endirim)": "(скидка {0}%)",
    "Keçən gün": "Прошло дней",
    "Çekin qaytarma müddəti bitib: {0} gün keçib (limit {1} gün).": "Срок возврата по чеку истёк: прошло {0} дн. (лимит {1} дн.).",
    "Qaytarılan say: {0}": "Количество возврата: {0}",
    "\"{0}\": ən çox {1} ədəd qaytarmaq olar (satılıb {2})": "«{0}»: можно вернуть не более {1} шт. (продано {2})",
    "məs. zədəli, uyğun gəlmədi": "напр. брак, не подошёл",
    "Satılıb": "Продано",
    "Qaytarılıb": "Возвращено",
    "Qaytarılır": "Возвращается",
    "Səbəb": "Причина",
    "Qaytarılacaq say yazın": "Введите количество к возврату",
    "\"{0}\": satılıb {1}, əvvəl qaytarılıb {2} — ən çox {3} ədəd qaytarmaq olar": "«{0}»: продано {1}, ранее возвращено {2} — можно вернуть не более {3} шт.",
    "Çek № {0} üzrə {1} ₼ qaytarılır.": "По чеку № {0} возвращается {1} ₼.",
    "Qaytarmanı təsdiqlə": "Подтвердить возврат",
    "{0} qaytarma istəyir. Çek № {1} üzrə {2} ₼ qaytarılır.": "{0} просит возврат. По чеку № {1} возвращается {2} ₼.",
    "Qaytarıldı: {0} ₼{1}": "Возвращено: {0} ₼{1}",
    "(nağd {0})": "(наличными {0})",
    "Qaytar": "Вернуть",
    "Çekin barkodunu oxudun və ya çek nömrəsini yazın": "Отсканируйте штрихкод чека или введите номер чека",
    "Açıq növbə yoxdur. Kassa ekranından açın.": "Нет открытой смены. Откройте её на экране кассы.",
    "Sayılmış məbləği yazın": "Введите пересчитанную сумму",
    "Növbə yoxlanılır və bağlanır…": "Смена проверяется и закрывается…",
    "Növbə bağlandı. Fərq: {0} ₼": "Смена закрыта. Разница: {0} ₼",
    "Bağla və Z hesabatı çap et": "Закрыть и напечатать Z-отчёт",
    "Açılıb: {0} · {1}": "Открыта: {0} · {1}",
    "Çek sayı": "Количество чеков",
    "Satış (endirimdən əvvəl)": "Продажи (до скидки)",
    "Nağd satış": "Продажи наличными",
    "Qaytarmalar": "Возвраты",
    "Kassaya mədaxil": "Внесение в кассу",
    "Kassadan məxaric": "Изъятие из кассы",
    "Başlanğıc nağd": "Начальные наличные",
    "Kassada olmalı nağd": "Должно быть наличных в кассе",
    "Növbəni bağla": "Закрыть смену",
    "Sayılmış nağd, ₼": "Пересчитано наличных, ₼",
    "Fərq varsa izah": "Объяснение, если есть разница",
    "Bank cəmlərini (POS və köçürmə) gün sonu bank çıxarışı ilə tutuşdurun.": "Сверьте банковские итоги (POS и переводы) с банковской выпиской в конце дня.",
    "Məbləğ, ₼": "Сумма, ₼",
    "Məxarici təsdiqlə": "Подтвердить изъятие",
    "{0} ₼ kassadan çıxarılır: {1}": "Из кассы изымается {0} ₼: {1}",
    "{0} kassadan məxaric istəyir: {1} ₼ ({2})": "{0} просит изъять из кассы {1} ₼ ({2})",
    "Qeydə alındı": "Записано",
    "Açılış": "Открытие",
    "Bağlanış": "Закрытие",
    "Satış": "Продажи",
    "Köçürmə": "Перевод",
    "Gözlənilən nağd": "Ожидаемые наличные",
    "Sayılmış nağd": "Пересчитанные наличные",
    "Fərq": "Разница",
    "İzah": "Пояснение",
    "Z HESABATI": "Z-ОТЧЁТ",
    "Yekun ₼": "Итого ₼",
    "Hələ satış yoxdur": "Продаж пока нет",
    "Dublikat çek": "Дубликат чека",
    "Çek № {0} \"DUBLİKAT\" qeydi ilə çap olunur.": "Чек № {0} печатается с отметкой «ДУБЛИКАТ».",
    "Dublikat": "Дубликат",
    "Rollar və icazələr": "Роли и права",
    "Hansı rolun hansı əməliyyata icazəsi olduğunu yalnız Admin dəyişir. Hər dəyişiklik audit jurnalına yazılır.": "Какие права есть у какой роли, меняет только Админ. Каждое изменение записывается в журнал аудита.",
    "İcazə": "Право",
    "İcazələr yadda saxlanıldı": "Права сохранены",
    "Mağaza adı": "Название магазина",
    "Ünvan": "Адрес",
    "Kassa adı": "Название кассы",
    "Sinxron açarı (SYNC_TOKEN)": "Ключ синхронизации (SYNC_TOKEN)",
    "Dəyişmək üçün yazın": "Введите, чтобы изменить",
    "Saxlanılıb · dəyişmək üçün yazın": "Сохранено · введите, чтобы изменить",
    "server qoşulub": "сервер подключён",
    "server qoşulmayıb (yalnız bu cihaz)": "сервер не подключён (только это устройство)",
    "· göndərilməmiş: {0}": "· не отправлено: {0}",
    "· son sinxron: {0}": "· последняя синхронизация: {0}",
    "Son xəta: {0}": "Последняя ошибка: {0}",
    "Sinxron alınmadı: {0}": "Синхронизация не удалась: {0}",
    "Ünvan yoxdur və ya oflayn": "Адреса нет или нет сети",
    "{0} qeyd göndərildi, {1} qeyd alındı": "Отправлено записей: {0}, получено: {1}",
    "Mağaza və server": "Магазин и сервер",
    "Ünvan boşdursa, sistem yalnız bu kompyuterdə işləyir. Hər yeni brauzer/cihaz bir dəfə qoşulmalıdır (giriş ekranında \"Bu cihazı serverə qoş\").": "Если адрес пуст, система работает только на этом компьютере. Каждый новый браузер/устройство нужно подключить один раз (на экране входа «Подключить это устройство к серверу»).",
    "Bağlantını yoxla": "Проверить соединение",
    "İndi sinxronlaşdır": "Синхронизировать сейчас",
    "{0} üçün müvəqqəti PIN bir dəfə göstərilir. İndi ötürün: ilk girişdə özünün yeni PIN-ini seçəcək.": "Временный PIN для {0} показывается один раз. Передайте его сейчас: при первом входе пользователь выберет свой новый PIN.",
    "PIN dəyişməlidir": "Нужно сменить PIN",
    "PIN-i sıfırla": "Сбросить PIN",
    "Məs. Elvin Babayev": "Напр. Эльвин Бабаев",
    "Yeni istifadəçi": "Новый пользователь",
    "Ad və soyad": "Имя и фамилия",
    "Rol": "Роль",
    "Müvəqqəti PIN yaradılacaq; istifadəçi ilk girişdə öz PIN-ini seçir.": "Будет создан временный PIN; пользователь выберет свой PIN при первом входе.",
    "Yarat": "Создать",
    "İstifadəçi yaradıldı": "Пользователь создан",
    "Redaktə — {0}": "Редактирование — {0}",
    "Öz rolunuzu dəyişə bilməzsiniz.": "Вы не можете изменить свою роль.",
    "Rol dəyişəndə istifadəçinin açıq cihazında menyu və icazələr bir neçə saniyəyə yenilənir.": "При смене роли меню и права на открытом устройстве пользователя обновятся за несколько секунд.",
    "Dəyişiklik yoxdur": "Изменений нет",
    "İstifadəçi artıq daxil ola bilməyəcək, açıq cihazlarda isə bir neçə saniyəyə çıxış edəcək. Keçmiş çeklər və hesabatlar saxlanılır.": "Пользователь больше не сможет войти, а на открытых устройствах выйдет из системы за несколько секунд. Прошлые чеки и отчёты сохраняются.",
    "İstifadəçi yenidən daxil ola biləcək (PIN dəyişməyibsə köhnə PIN ilə).": "Пользователь снова сможет войти (со старым PIN, если он не менялся).",
    "PIN-i sıfırla — {0}": "Сброс PIN — {0}",
    "Müvəqqəti PIN yaradılacaq. İstifadəçi ilk girişdə özünün yeni PIN-ini seçəcək. Köhnə PIN dərhal etibarsız olur.": "Будет создан временный PIN. При первом входе пользователь выберет свой новый PIN. Старый PIN сразу перестаёт действовать.",
    "Sıfırla": "Сбросить",
    "Müvəqqəti PIN": "Временный PIN",
    "İstifadəçilər": "Пользователи",
    "+ Yeni istifadəçi": "+ Новый пользователь",
    "Hesabınız söndürülüb. Yenidən daxil olun": "Ваша учётная запись отключена. Войдите заново",
    "Bu əməliyyata icazəniz yoxdur: {0}": "У вас нет права на это действие: {0}",
    "Nömrə ehtiyatı bitib. İnternetə qoşulun və bir neçə saniyə gözləyin": "Резерв номеров закончился. Подключитесь к интернету и подождите несколько секунд",
    "İstifadəçi tapılmadı": "Пользователь не найден",
    "Çox səhv cəhd. {0} dəqiqə gözləyin": "Слишком много неверных попыток. Подождите {0} мин.",
    "PIN səhvdir": "Неверный PIN",
    "PIN 4–8 rəqəm olmalıdır": "PIN должен состоять из 4–8 цифр",
    "Yeni PIN köhnə PIN ilə eyni ola bilməz": "Новый PIN не может совпадать со старым",
    "Çox sadə PIN seçməyin": "Не выбирайте слишком простой PIN",
    "Köhnə PIN səhvdir": "Старый PIN неверен",
    "Ad ən azı 2 simvol olmalıdır": "Имя должно содержать не менее 2 символов",
    "Ad 40 simvoldan uzun ola bilməz": "Имя не может быть длиннее 40 символов",
    "Bu adda istifadəçi artıq var": "Пользователь с таким именем уже есть",
    "Rol seçin": "Выберите роль",
    "Rol səhvdir": "Неверная роль",
    "Öz hesabınızı söndürə bilməzsiniz": "Нельзя отключить свою учётную запись",
    "Sistemdə ən azı bir aktiv Admin qalmalıdır": "В системе должен остаться хотя бы один активный Админ",
    "PIN yanlışdır və ya bu şəxsin təsdiq icazəsi yoxdur": "PIN неверен или у этого человека нет права подтверждения",
    "Məhsulun adı boşdur": "Название товара пустое",
    "Satış qiyməti 0-dan böyük olmalıdır": "Цена продажи должна быть больше 0",
    "İstehsalçı barkodunda boşluq ola bilməz": "В штрихкоде производителя не может быть пробелов",
    "Bu, mağaza və ya çek barkodudur, istehsalçı barkodu deyil": "Это штрихкод магазина или чека, а не производителя",
    "Satış qiymətini yalnız Menecer və Admin təyin edir": "Цену продажи назначают только Менеджер и Админ",
    "Bu istehsalçı barkodu artıq var: {0}": "Такой штрихкод производителя уже есть: {0}",
    "Məhsul tapılmadı": "Товар не найден",
    "Təchizatçının adı ən azı 2 simvol olmalıdır": "Название поставщика должно содержать не менее 2 символов",
    "Ad 60 simvoldan uzun ola bilməz": "Название не может быть длиннее 60 символов",
    "Bu adda təchizatçı artıq var": "Поставщик с таким названием уже есть",
    "Telefon çox uzundur": "Слишком длинный телефон",
    "Qeyd 300 simvoldan uzun ola bilməz": "Примечание не может быть длиннее 300 символов",
    "Təchizatçı tapılmadı": "Поставщик не найден",
    "Say müsbət tam ədəd olmalıdır": "Количество должно быть целым положительным числом",
    "Təchizatçı tapılmadı və ya söndürülüb": "Поставщик не найден или отключён",
    "Silinmiş təchizatçı": "Удалённый поставщик",
    "Təchizatçısız (köhnə qalıq / mənfi satış)": "Без поставщика (старый остаток / продажа в минус)",
    "Başlanğıc nağdı yazın": "Введите начальные наличные",
    "Artıq açıq növbə var": "Смена уже открыта",
    "Əvvəlki növbədən qalıq {0} ₼ idi. Fərqli məbləğ üçün izah yazın": "Остаток с предыдущей смены был {0} ₼. Для другой суммы напишите объяснение",
    "Səbəbi yazın": "Укажите причину",
    "Kassadan məxaric menecer təsdiqi tələb edir": "Изъятие из кассы требует подтверждения менеджера",
    "Növbə açıq deyil": "Смена не открыта",
    "Kassa fərqi var ({0} ₼). İzah yazın": "В кассе есть разница ({0} ₼). Напишите объяснение",
    "Açıq növbə yoxdur": "Нет открытой смены",
    "Sinxronlaşmamış {0} qeyd var. İnternet qayıdana qədər növbə bağlanmır (FR-104)": "Есть несинхронизированных записей: {0}. Пока нет интернета, смена не закрывается (FR-104)",
    "Endirim menecer tərəfindən təsdiqlənməyib": "Скидка не подтверждена менеджером",
    "Satış üçün növbəni açın": "Откройте смену для продаж",
    "Məhsul satışda deyil": "Товар снят с продажи",
    "Say səhvdir: {0}": "Неверное количество: {0}",
    "\"{0}\" qalığı yoxdur və artıq {1} mənfi çekdə satılıb. Mal qəbulu daxil edin": "Остатка «{0}» нет, и он уже продан в {1} чеках с отрицательным остатком. Оформите приход товара",
    "Çekin qaytarma müddəti bitib ({0} gün keçib, limit {1} gün)": "Срок возврата по чеку истёк (прошло {0} дн., лимит {1} дн.)",
    "Sətir tapılmadı": "Строка не найдена",
    "\"{0}\": say tam müsbət ədəd olmalıdır": "«{0}»: количество должно быть целым положительным числом",
    "Qaytarma menecer təsdiqi tələb edir": "Возврат требует подтверждения менеджера",
    "Qaytarma üçün növbəni açın": "Откройте смену для возврата",
    "\"{0}\" üzrə ən çox {1} ədəd qaytarmaq olar": "«{0}»: можно вернуть не более {1} шт.",
    "Qaytarılacaq məhsul seçin": "Выберите товар для возврата",
    "Admin icazə idarəsini özündən götürə bilməz": "Админ не может лишить себя управления правами",
    "Qərar səhvdir": "Неверное решение",
    "Sorğu tapılmadı": "Запрос не найден",
    "Öz sorğunuzu təsdiqləyə bilməzsiniz": "Нельзя подтвердить собственный запрос",
    "Sorğuya artıq cavab verilib": "На запрос уже ответили",
    "Sorğunun vaxtı bitib": "Срок запроса истёк",
    "Ünvan boşdur": "Адрес пуст",
    "Bu /dev ünvanıdır, o yalnız sizin brauzerinizdə işləyir. Deploy → Manage deployments bölməsindən /exec ilə bitən ünvanı götürün": "Это адрес /dev, он работает только в вашем браузере. В разделе Deploy → Manage deployments возьмите адрес, оканчивающийся на /exec",
    "Bu Apps Script redaktorunun linkidir. Deploy → Manage deployments → Web app URL lazımdır": "Это ссылка на редактор Apps Script. Нужен Deploy → Manage deployments → Web app URL",
    "Ünvan https://script.google.com/macros/s/…/exec formasında olmalıdır": "Адрес должен быть вида https://script.google.com/macros/s/…/exec",
    "{0}. İnterneti yoxlayın; Apps Script bəzən yavaş cavab verir, sinxron özü təkrar cəhd edəcək": "{0}. Проверьте интернет; Apps Script иногда отвечает медленно, синхронизация повторит попытку сама",
    "Server cavab vermədi. Ən çox səbəb: Deploy-da \"Who has access\" = \"Anyone\" deyil (yalnız Google hesabına girmiş brauzerdə işləyir, digər brauzerdə yox). Yoxlama: ünvanı gizli pəncərədə açın, {\"ok\":true} görünməlidir. Kodu dəyişəndən sonra \"New version\" deploy etmək də lazımdır": "Сервер не ответил. Чаще всего причина: в Deploy «Who has access» ≠ «Anyone» (работает только в браузере, где выполнен вход в Google, в других — нет). Проверка: откройте адрес в окне инкогнито, должно появиться {\"ok\":true}. После изменения кода также нужно сделать deploy «New version»",
    "Server JSON əvəzinə səhifə qaytardı (çox güman Google giriş səhifəsi və ya Apps Script limiti). Deploy-da \"Who has access\" = \"Anyone\" olmalıdır": "Сервер вернул страницу вместо JSON (скорее всего страницу входа Google или лимит Apps Script). В Deploy «Who has access» должно быть «Anyone»",
    "Server {0} san ərzində cavab vermədi": "Сервер не ответил за {0} с",
    "Sorğu dayandırıldı": "Запрос прерван",
    "Server {0}": "Сервер {0}",
    "Açar uyğun gəlmir: tətbiqdəki açar Script properties-dəki SYNC_TOKEN ilə eyni olmalıdır": "Ключ не совпадает: ключ в приложении должен быть таким же, как SYNC_TOKEN в Script properties",
    "Server xətası": "Ошибка сервера",
    "Cavab gəldi, amma bu, mağaza skripti deyil": "Ответ пришёл, но это не скрипт магазина",
    "Skriptdə SYNC_TOKEN təyin olunmayıb (Project Settings → Script properties)": "В скрипте не задан SYNC_TOKEN (Project Settings → Script properties)",
    "Skriptin köhnə versiyası işləyir. Yeni Code.gs-i yapışdırın və Deploy → Manage deployments → Edit → New version seçin": "Работает старая версия скрипта. Вставьте новый Code.gs и выберите Deploy → Manage deployments → Edit → New version",
    "Cədvəllərdə çatışmayan vərəqlər: {0}. setup() funksiyasını işə salın": "В таблицах не хватает листов: {0}. Запустите функцию setup()",
    "Bağlantı işləyir{0}": "Соединение работает{0}",
    ". Diqqət: skript köhnədir (v{0}). {1}{2}telefona bildiriş üçün yeni Code.gs-i yapışdırın, setup() işlədin və \"New version\" deploy edin (tətbiq bu olmadan da işləyir, məlumat Events vərəqində saxlanılır)": ". Внимание: скрипт устарел (v{0}). {1}{2}для уведомлений на телефон вставьте новый Code.gs, запустите setup() и сделайте deploy «New version» (приложение работает и без этого, данные хранятся на листе Events)",
    "Sürətli sinxron və keş düzəlişi,": "быстрая синхронизация и исправление кэша,",
    "təchizatçı/partiya cədvəllərinin Sheets-ə yazılması,": "запись листов поставщиков/партий в Sheets,",
    "Server qoşulmayıb": "Сервер не подключён",
    "Açarı (SYNC_TOKEN) yazın": "Введите ключ (SYNC_TOKEN)",
    "Ləğv et": "Отменить",
    "Menecer PIN-ini yazın və ya sorğu göndərin: menecer öz cihazında təsdiqləyəcək.": "Введите PIN менеджера или отправьте запрос: менеджер подтвердит на своём устройстве.",
    "Menecer PIN-ini yazın.": "Введите PIN менеджера.",
    "Menecer PIN-i": "PIN менеджера",
    "Menecer təsdiqlədi": "Менеджер подтвердил",
    "Menecer sorğunu rədd etdi": "Менеджер отклонил запрос",
    "Sorğunun vaxtı bitdi": "Срок запроса истёк",
    "Menecerə sorğu göndər": "Отправить запрос менеджеру",
    "Sorğu üçün internet lazımdır. Menecer PIN-i ilə təsdiqləyin": "Для запроса нужен интернет. Подтвердите PIN-кодом менеджера",
    "Sorğu menecerə göndərildi, cavab gözlənilir: {0}": "Запрос отправлен менеджеру, ожидается ответ: {0}",
    "Sorğu ləğv edildi": "Запрос отменён",
    "Sorğu menecerə göndərildi": "Запрос отправлен менеджеру",
    "Qaytarılan@@change": "Сдача",
    "JSON səhvdir": "Некорректный JSON",
    "Naməlum əməliyyat": "Неизвестная операция",
    "Naməlum açar": "Неизвестный ключ",
    "Server məşğuldur, sonra təkrar olunacaq": "Сервер занят, повтор позже",
    "Bildiriş ünvanı tanınmır": "Адрес уведомлений не распознан",
    "Bu cihaz bildiriş üçün qeydiyyatdan keçməyib": "Это устройство не зарегистрировано для уведомлений",
    "Mal qəbulu sorğusu göndərmək (menecer təsdiqləyir)": "Отправлять запрос на приём товара (подтверждает менеджер)",
    "Qəbul təsdiqləndi, qalıq artırıldı: {0} ədəd": "Приём подтверждён, остаток увеличен: {0} шт.",
    "Hazırkı qalıq: {0}": "Текущий остаток: {0}",
    "Təsdiqlə və qəbul et": "Подтвердить и принять",
    "Mal gəldi: menecerə təsdiq sorğusu göndər": "Товар пришёл: отправить менеджеру запрос на подтверждение",
    "Mal gəldi": "Товар пришёл",
    "Gözləyir": "Ожидает",
    "Ləğv edildi": "Отменён",
    "Vaxtı bitib": "Срок истёк",
    "Mal qəbulu sorğularım": "Мои запросы на приём товара",
    "Qalıq menecer təsdiqləyəndən sonra artır.": "Остаток увеличится после подтверждения менеджером.",
    "Vaxt": "Время",
    "— bilmirəm / menecer seçəcək —": "— не знаю / выберет менеджер —",
    "Mal gəldi — {0}": "Товар пришёл — {0}",
    "Gələn malın sayını yazın. Sorğu menecerə gedir; qalıq menecer təsdiqləyəndən sonra artacaq (hazırkı qalıq: {0}).": "Укажите количество пришедшего товара. Запрос уйдёт менеджеру; остаток увеличится после его подтверждения (текущий остаток: {0}).",
    "Server qoşulmayıb: sorğu menecerin cihazına çata bilməz. Mal qəbulunu menecer özü etməlidir": "Сервер не подключён: запрос не дойдёт до устройства менеджера. Приём товара должен оформить сам менеджер.",
    "Say {0}-dən çox ola bilməz": "Количество не может быть больше {0}",
    "Qeyd 200 simvoldan uzun ola bilməz": "Примечание не может быть длиннее 200 символов",
    "Bu məhsul üçün sorğu artıq menecerin cavabını gözləyir. Dəyişmək istəyirsinizsə əvvəl onu ləğv edin": "Запрос по этому товару уже ждёт ответа менеджера. Чтобы изменить, сначала отмените его.",
    "{0} mal qəbulu istəyir: «{1}», {2} ədəd": "{0} просит принять товар: «{1}», {2} шт.",
    "Saat səhvdir": "Неверные часы",
    "Bu cihazın saatı serverdən {0} dəq. fərqlənir. Çek tarixləri avtomatik düzəldilir, amma cihazın saatını \"avtomatik\" rejimə keçirin": "Часы устройства отличаются от сервера на {0} мин. Даты чеков исправляются автоматически, но включите на устройстве автоматическое время",
    "Bir çekdə ən çox {0} sətir ola bilər. Çeki iki hissəyə bölün": "В одном чеке может быть не более {0} позиций. Разделите чек на две части",
    "Yüklənir…": "Загрузка…",
    "Arxivləşdirilir… 1–5 dəqiqə çəkə bilər, pəncərəni bağlamayın.": "Архивация… может занять 1–5 минут, не закрывайте окно.",
    "Arxivləşdirmə": "Архивация",
    "Son {0} gündən köhnə qeydlər Drive-da yeni arxiv faylına köçürüləcək. 1–5 dəqiqə çəkə bilər: bu müddətdə kassa işləyir, amma sinxron gecikə bilər. İş saatından sonra edin.": "Записи старше последних {0} дн. будут перенесены в новый архивный файл на Диске. Может занять 1–5 минут: касса продолжает работать, но синхронизация может задерживаться. Делайте это после рабочего времени.",
    "Arxivləşdir": "Архивировать",
    "Arxivləşdirməyə dəyər köhnə qeyd yoxdur: {0} gündən köhnə kifayət qədər qeyd yoxdur": "Архивировать нечего: недостаточно записей старше {0} дн.",
    "Arxivləşdirildi: {0} hadisə köçürüldü. Cədvəl tutumu: {1}%": "Архивация завершена: перенесено событий: {0}. Заполнено таблицы: {1}%",
    "Cədvəl tutumu: {0}% ({1} / {2} xana)": "Заполнено: {0}% ({1} / {2} ячеек)",
    "Cədvəl tutumu": "Заполнение таблицы",
    "Hadisə: canlı {0} · arxivdə {1} · cəmi {2}": "События: активных {0} · в архиве {1} · всего {2}",
    "Son arxivləşdirmə: {0}": "Последняя архивация: {0}",
    "Hələ arxivləşdirilməyib": "Архивация ещё не проводилась",
    "Tutum dolmağa yaxınlaşır. İş saatından sonra arxivləşdirin.": "Таблица заполняется. Проведите архивацию после рабочего времени.",
    "Arxivləşdirmə son {0} gündən köhnə qeydləri Drive-da yeni arxiv faylına köçürür, cədvəldə yalnız yeni qeydləri saxlayır. Heç nə itmir, cihazlar heç nə etmir.": "Архивация переносит записи старше последних {0} дн. в новый архивный файл на Диске и оставляет в таблице только свежие. Ничего не теряется, устройствам ничего делать не нужно.",
    "Köhnə qeydləri arxivləşdir": "Архивировать старые записи",
    "Yenilə": "Обновить",
    "Hadisələr": "События",
    "Köçürülən": "Перенесено",
    "Fayl": "Файл",
    "Aç": "Открыть",
    "Arxiv fayllarını silməyin. Onları Drive-da başqa qovluğa köçürə bilərsiniz.": "Не удаляйте архивные файлы. Их можно переместить в другую папку на Диске.",
    "Skript köhnədir: yeni Code.gs (v7) yerləşdirin, setup() işlədin və Deploy → New version edin.": "Скрипт устарел: вставьте новый Code.gs (v7), запустите setup() и сделайте Deploy → New version.",
    "Arxiv məlumatı alınmadı: {0}": "Не удалось получить данные архива: {0}",
    "Arxiv (Google Sheets tutumu)": "Архив (заполнение Google Sheets)",
    "Cədvəl tutumunun {0}%-i dolub. Rollar və icazələr → Arxiv bölməsində arxivləşdirin": "Таблица заполнена на {0}%. Проведите архивацию: Роли и права → Архив",
    "Təsdiq lazımdır": "Требуется подтверждение",
    "Arxivləşdirmə gedir, bir neçə dəqiqə sonra təkrar olunacaq": "Идёт архивация, повтор через несколько минут",
    "Son arxivləşdirmədən 24 saat keçməyib ({0} UTC)": "С последней архивации прошло менее 24 часов ({0} UTC)",
    "Şifrədə boşluq ola bilməz": "В пароле не должно быть пробелов",
    "Şifrə ən azı {0} simvol olmalıdır": "Пароль должен содержать не менее {0} символов",
    "Şifrə {0} simvoldan uzun ola bilməz": "Пароль не может быть длиннее {0} символов",
    "Şifrədə ən azı 1 böyük hərf olmalıdır": "В пароле должна быть хотя бы 1 заглавная буква",
    "Şifrədə ən azı 1 kiçik hərf olmalıdır": "В пароле должна быть хотя бы 1 строчная буква",
    "Şifrədə ən azı 1 rəqəm olmalıdır": "В пароле должна быть хотя бы 1 цифра",
    "Şifrədə ən azı 1 işarə olmalıdır (məs. ! ? . # $ %)": "В пароле должен быть хотя бы 1 символ (напр. ! ? . # $ %)",
    "Giriş forması səhvdir": "Недопустимая форма входа",
    "Şifrə səhvdir": "Неверный пароль",
    "Köhnə şifrə səhvdir": "Текущий пароль неверен",
    "Yeni şifrə köhnə kodla eyni ola bilməz": "Новый пароль не может совпадать с текущим кодом",
    "Şifrə": "Пароль",
    "Bu istifadəçinin giriş forması dəyişib. Yeni formada yazın": "Форма входа этого пользователя изменилась. Введите в новой форме",
    "Yeni şifrə təyin edin": "Задайте новый пароль",
    "İşə başlamazdan əvvəl yalnız sizə məlum olan şifrə seçin: ən azı {0} simvol, 1 böyük hərf, 1 kiçik hərf, 1 rəqəm və 1 işarə.": "Прежде чем начать, задайте пароль, известный только вам: не менее {0} символов, 1 заглавная буква, 1 строчная буква, 1 цифра и 1 символ.",
    "Administrator bu rol üçün giriş formasını dəyişib. Hazırkı kodunuzla daxil oldunuz, indi yenisini seçin.": "Администратор изменил форму входа для этой роли. Вы вошли с текущим кодом, теперь выберите новый.",
    "Hazırkı şifrə": "Текущий пароль",
    "Yeni şifrə": "Новый пароль",
    "Yeni şifrə təkrar": "Повторите новый пароль",
    "Yeni şifrələr eyni deyil": "Новые пароли не совпадают",
    "Şifrə dəyişdirildi": "Пароль изменён",
    "PIN (4–8 rəqəm)": "PIN (4–8 цифр)",
    "Şifrə (hərf, rəqəm, işarə)": "Пароль (буквы, цифра, символ)",
    "{0} nəfər növbəti girişdə dəyişəcək": "{0} польз. перейдут при следующем входе",
    "Giriş forması": "Форма входа",
    "Şifrə qaydası: ən azı {0} simvol, 1 böyük hərf, 1 kiçik hərf, 1 rəqəm, 1 işarə. Forma dəyişəndə həmin roldakılar öz hazırkı kodu ilə daxil olur və dərhal yenisini seçməlidir. Açıq sessiyalar bağlanmır, məcburi dəyişmə növbəti girişdə olur.": "Правило пароля: не менее {0} символов, 1 заглавная буква, 1 строчная буква, 1 цифра, 1 символ. При смене формы сотрудники этой роли входят с текущим кодом и сразу должны выбрать новый. Открытые сеансы не закрываются, принудительная смена происходит при следующем входе.",
    "Giriş forması (rol üzrə)": "Форма входа (по ролям)",
    "{0} üçün müvəqqəti şifrə bir dəfə göstərilir. İndi ötürün: ilk girişdə özünün yeni şifrəsini seçəcək.": "Временный пароль для {0} показывается один раз. Передайте его сейчас: при первом входе сотрудник выберет свой новый пароль.",
    "Şifrə dəyişməlidir": "Нужно сменить пароль",
    "Şifrəni sıfırla": "Сбросить пароль",
    "Müvəqqəti şifrə yaradılacaq; istifadəçi ilk girişdə öz şifrəsini seçir.": "Будет создан временный пароль; пользователь выберет свой при первом входе.",
    "Bu rolun giriş forması fərqlidir: istifadəçi növbəti girişdə öz hazırkı kodu ilə daxil olub yenisini seçəcək.": "У этой роли другая форма входа: при следующем входе пользователь войдёт с текущим кодом и выберет новый.",
    "Şifrəni sıfırla — {0}": "Сбросить пароль — {0}",
    "Müvəqqəti şifrə yaradılacaq. İstifadəçi ilk girişdə özünün yeni şifrəsini seçəcək. Köhnə kod dərhal etibarsız olur.": "Будет создан временный пароль. При первом входе пользователь выберет новый. Старый код сразу перестаёт действовать.",
    "Müvəqqəti şifrə": "Временный пароль",
    "Menecerin PIN-ini və ya şifrəsini yazın, ya da sorğu göndərin: menecer öz cihazında təsdiqləyəcək.": "Введите PIN или пароль менеджера либо отправьте запрос: менеджер подтвердит на своём устройстве.",
    "Menecerin PIN-ini və ya şifrəsini yazın.": "Введите PIN или пароль менеджера.",
    "Menecer PIN-i və ya şifrəsi": "PIN или пароль менеджера"
  });
})(typeof window !== 'undefined' ? window : globalThis);
