/* Ingilis dili tərcümələri (açar = Azərbaycanca mənbə mətni). Yeni mətn əlavə edəndə: node tools/i18n-scan.js --missing və npm test. */
(function (root) {
  'use strict';
  root.I18n.add('en', {
    "Kassa": "Checkout",
    "Qaytarma": "Returns",
    "Məhsullar": "Products",
    "Təchizatçılar": "Suppliers",
    "Çeklər": "Receipts",
    "Növbə": "Shift",
    "İcazələr": "Permissions",
    "Bu rol üçün açıq ekran yoxdur.": "No screens are available for this role.",
    "Onlayn": "Online",
    "Oflayn": "Offline",
    "Google Apps Script serverinin orta cavab müddəti. Cihazlar arasında yenilik təxminən bunun 2–3 qatı qədər gecikir": "Average response time of the Google Apps Script server. Updates reach other devices in roughly 2–3 times this delay.",
    "Server {0} san": "Server {0} s",
    "Tətbiq versiyası. İki cihazda eyni olmalıdır; fərqlidirsə Ctrl+F5 basın": "App version. It must be the same on both devices; if it differs, press Ctrl+F5",
    "Serverə göndərilməmiş qeydlər": "Records not yet sent to the server",
    "{0} sinxron gözləyir": "{0} waiting to sync",
    "Sinxron xətası": "Sync error",
    "Sorğular ({0})": "Requests ({0})",
    "Növbə açıq · {0}": "Shift open · {0}",
    "Növbə bağlı": "Shift closed",
    "Təsdiq sorğusu gələndə telefona/brauzerə bildiriş": "Notification to your phone/browser when an approval request arrives",
    "Bildiriş": "Notifications",
    "Bu cihazın printeri: kağız eni, etiket ölçüsü, test çapı": "This device's printer: paper width, label size, test print",
    "Çap": "Print",
    "Çıxış": "Log out",
    "Yeni təsdiq sorğusu: {0}": "New approval request: {0}",
    "Hesabınız dəyişdirilib və ya söndürülüb. Yenidən daxil olun": "Your account was changed or disabled. Please sign in again",
    "Bölmələr": "Sections",
    "Mağaza İS — Kassa": "Store System — Checkout",
    "Başlatma xətası: {0}": "Startup error: {0}",
    "Bildiriş yalnız təhlükəsiz (https) ünvanda işləyir": "Notifications only work on a secure (https) address",
    "iPhone/iPad-də bildiriş yalnız tətbiq ana ekrana əlavə edilibsə işləyir: Safari → Paylaş → \"Ana ekrana əlavə et\", sonra oradan açın (iOS 16.4 və yuxarı)": "On iPhone/iPad notifications only work if the app is added to the Home Screen: Safari → Share → \"Add to Home Screen\", then open it from there (iOS 16.4 or later)",
    "Bu brauzer bildirişi dəstəkləmir. Chrome, Edge və ya Firefox-un yeni versiyasından istifadə edin": "This browser does not support notifications. Use a recent version of Chrome, Edge or Firefox",
    "Xidmət işçisi (service worker) işləmir. Səhifəni yeniləyin (Ctrl+F5); tətbiq https ünvanından açılmalıdır": "The service worker is not running. Reload the page (Ctrl+F5); the app must be opened from an https address",
    "Server skripti köhnədir: Code.gs-in v6 versiyasını yapışdırın, setup() işlədin və \"New version\" deploy edin": "The server script is outdated: paste Code.gs version v6, run setup() and deploy a \"New version\"",
    "Apps Script-də V8 runtime aktiv deyil (BigInt yoxdur): Project Settings → \"Chrome V8 runtime\" seçin, sonra New version deploy edin. Sinxron təsirlənmir, yalnız bildiriş işləmir": "The V8 runtime is not enabled in Apps Script (BigInt missing): Project Settings → select \"Chrome V8 runtime\", then deploy a New version. Sync is not affected, only notifications don't work",
    "Apps Script-ə xarici sorğu icazəsi verilməyib: redaktorda setup() işlədin, \"Connect to an external service\" icazəsini təsdiqləyin və yenidən \"New version\" deploy edin": "Apps Script has not been granted permission for external requests: run setup() in the editor, approve \"Connect to an external service\" and deploy a \"New version\" again",
    "Əvvəl serveri qoşun (İcazələr → Mağaza və server)": "Connect the server first (Permissions → Store and server)",
    "Daxil olun": "Please sign in",
    "Bildiriş bloklanıb. Brauzerin ünvan sətrindəki qıfıl işarəsi → Bildirişlər → \"İcazə ver\", sonra yenidən basın": "Notifications are blocked. Lock icon in the browser address bar → Notifications → \"Allow\", then click again",
    "Bildiriş icazəsi verilmədi": "Notification permission was not granted",
    "Bu rolun təsdiq sorğusu almaq icazəsi yoxdur": "This role cannot receive approval requests",
    "Təsdiq sorğusu": "Approval request",
    "Kassadan menecer təsdiqi gözlənilir": "The cashier is waiting for manager approval",
    "Mağaza İS — test": "Store System — test",
    "Bildirişlər bu cihazda işləyir.": "Notifications work on this device.",
    "Bu cihaz push üçün qoşulmayıb. \"Aktiv et\" düyməsini basın": "This device is not subscribed to push. Press \"Enable\"",
    "Kassir təsdiq sorğusu göndərəndə (sətir silmə, endirim, qaytarma) bu cihaza bildiriş gəlsin. Hər menecer cihazında bir dəfə aktiv edilir.": "When a cashier sends an approval request (line removal, discount, return), this device gets a notification. Enabled once on each manager device.",
    "Brauzer icazəsi verilib": "Browser permission granted",
    "Brauzer bildirişi bloklayıb (ünvan sətrindəki qıfıldan açın)": "The browser has blocked notifications (unblock via the lock icon in the address bar)",
    "Brauzer icazəsi hələ verilməyib": "Browser permission not granted yet",
    "Bu cihaz bildirişə qoşulub": "This device is subscribed to notifications",
    "Bu cihaz bildirişə qoşulmayıb": "This device is not subscribed to notifications",
    "Bu rolun təsdiq sorğusu almaq icazəsi yoxdur (Menecer və ya Admin daxil olmalıdır)": "This role cannot receive approval requests (sign in as Manager or Admin)",
    "Test bildirişi göndər": "Send test notification",
    "Söndür": "Disable",
    "Bildiriş aktiv edildi": "Notifications enabled",
    "Aktiv et": "Enable",
    "Göndərilir…": "Sending…",
    "Bu cihazda bildiriş göstərildi (ikon və səs yoxlanılır)": "A notification was shown on this device (check the icon and sound)",
    "Bu cihazda bildiriş göstərilmədi: {0}": "No notification was shown on this device: {0}",
    "naməlum səbəb": "unknown reason",
    "Server push xidmətinə göndərdi (cavab {0}). 5–15 saniyəyə \"Təsdiq sorğusu\" bildirişi gəlməlidir; tətbiqi başqa tabə keçirin": "The server sent it to the push service (response {0}). The \"Approval request\" notification should arrive within 5–15 seconds; switch to another tab",
    "Push xidməti rədd etdi (cavab {0}): {1}. Söndürüb yenidən aktiv edin": "The push service rejected it (response {0}): {1}. Disable and enable again",
    "Bildirişlər": "Notifications",
    "Bağla": "Close",
    "Yarımçıq çek bərpa olundu ({0} sətir)": "Unfinished receipt restored ({0} lines)",
    "\"{0}\" qalığı yoxdur və limit ({1} mənfi çek) dolub. Satmaq olmaz — mal qəbulu lazımdır (qəbulu menecer edir).": "\"{0}\" is out of stock and the limit ({1} negative-stock receipts) is used up. It cannot be sold — goods must be received first (the manager does the receiving).",
    "Diqqət: \"{0}\" qalığı {1}. Mənfi qalıqla satış {2}/{3} çek.": "Warning: \"{0}\" stock is {1}. Negative-stock sale {2}/{3} receipts.",
    "{0} əlavə olundu": "{0} added",
    "Bu istehsalçı barkodudur. Məhsulun üzərindəki mağaza barkodunu oxudun ({0}).": "This is a manufacturer barcode. Scan the store barcode on the item ({0}).",
    "Bu çek barkodudur. Qaytarma üçün \"Qaytarma\" bölməsinə keçin.": "This is a receipt barcode. Go to the \"Returns\" section to make a return.",
    "\"{0}\" satışdan çıxarılıb.": "\"{0}\" has been withdrawn from sale.",
    "Barkod tapılmadı: {0}": "Barcode not found: {0}",
    "Sayı 1-dən azaltmaq olmaz. Sətri silmək üçün zibil ikonuna basın (menecer təsdiqi lazımdır).": "Quantity cannot go below 1. To remove the line, press the trash icon (manager approval required).",
    "Bu sətir üçün sorğu artıq göndərilib, menecer cavabı gözlənilir": "A request for this line has already been sent; waiting for the manager's reply",
    "Sətri çekdən sil": "Remove line from receipt",
    "{0} çekdən çıxarılır.": "{0} is being removed from the receipt.",
    "{0} sətir silmək istəyir: {1}": "{0} wants to remove a line: {1}",
    "Təsdiq olunan {0} ədəd silindi, sətirdə {1} qaldı ({2} təsdiqlədi)": "Approved quantity {0} removed, {1} left in the line ({2} approved)",
    "Sətir silindi ({0} təsdiqlədi)": "Line removed ({0} approved)",
    "Çekin ləğvi üçün sorğu artıq göndərilib": "A request to cancel the receipt has already been sent",
    "Çeki ləğv et": "Cancel receipt",
    "Bütün çek ({0} ₼) ləğv olunur.": "The whole receipt ({0} ₼) is being cancelled.",
    "{0} çeki ləğv etmək istəyir: {1} ₼": "{0} wants to cancel the receipt: {1} ₼",
    "Çek arada dəyişdi, təsdiq olunmuş ləğv tətbiq edilmədi": "The receipt changed in the meantime; the approved cancellation was not applied",
    "Endirim sorğusu": "Discount request",
    "Endirim, % (ən çox {0}%)": "Discount, % (max {0}%)",
    "Endirimi götür": "Remove discount",
    "İmtina": "Cancel",
    "Menecerə göndər": "Send to manager",
    "{0}% endirim: {1} → {2} ₼": "{0}% discount: {1} → {2} ₼",
    "Endirimi təsdiqlə": "Approve discount",
    "{0} endirim istəyir: {1}% endirim: {2} → {3} ₼": "{0} asks for a discount: {1}%: {2} → {3} ₼",
    "Çek arada dəyişdi, təsdiqlənmiş endirim tətbiq edilmədi. Yenidən sorğu göndərin": "The receipt changed in the meantime; the approved discount was not applied. Send the request again",
    "{0}% endirim təsdiqləndi ({1})": "{0}% discount approved ({1})",
    "Endirim təsdiqlənmədi": "Discount was not approved",
    "Çek № {0} tamamlandı{1}{2}": "Receipt #{0} completed{1}{2}",
    "· qaytarılacaq {0} ₼": "change {0} ₼",
    "· ÇEK ÇAP OLUNMADI ({0}): Çeklər bölməsindən təkrar çap edin": "RECEIPT NOT PRINTED ({0}): reprint it from the Receipts section",
    "məs. say səhv idi, sayım nəticəsi": "e.g. miscount, result of recount",
    "Fərqin izahı (əvvəlki növbənin qalığından fərqlidir)": "Explain the difference (differs from the previous shift's balance)",
    "Məbləğ səhvdir": "Invalid amount",
    "Yoxlanılır…": "Checking…",
    "Növbə açıldı": "Shift opened",
    "Növbəni aç": "Open shift",
    "Növbə bağlıdır": "The shift is closed",
    "Satışa başlamaq üçün kassadakı başlanğıc nağdı sayıb yazın.": "To start selling, count the cash in the till and enter the opening amount.",
    "Əvvəlki növbədən kassada qalan nağd: {0} ₼ ({1}). Növbə bu məbləğlə başlayır; kassanı sayıb fərqli çıxsa dəyişin və izah yazın.": "Cash left in the till from the previous shift: {0} ₼ ({1}). The shift starts with this amount; if your count differs, change it and write an explanation.",
    "Başlanğıc nağd, ₼": "Opening cash, ₼",
    "Barkodu oxudun — məhsul burada görünəcək": "Scan a barcode — the item will appear here",
    "Qalıq yoxdur, limit dolub — satılmaz": "Out of stock, limit reached — cannot be sold",
    "Qalıq {0} · mənfi qalıqla satış {1}/{2}": "Stock {0} · negative-stock sale {1}/{2}",
    "Azalt": "Decrease",
    "Sətri silmək üçün zibil ikonu (menecer təsdiqi)": "Trash icon to remove the line (manager approval)",
    "Sayı azalt": "Decrease quantity",
    "Artır": "Increase",
    "{0} ədəd": "{0} pcs",
    "Menecer cavabı gözlənilir": "Waiting for the manager's reply",
    "Sətri sil (menecer təsdiqi lazımdır)": "Remove line (manager approval required)",
    "Sətri sil: {0}": "Remove line: {0}",
    "Nağd ödəniş": "Cash payment",
    "Bank ödənişi": "Bank payment",
    "Qarışıq ödəniş": "Split payment",
    "Bank növü": "Bank payment type",
    "POS kart": "Card (POS)",
    "Karta köçürmə": "Card transfer",
    "Bank hissəsi, ₼": "Bank portion, ₼",
    "Müştəridən alınan nağd, ₼ (boş qoysanız — dəqiq nağd hissə)": "Cash received from the customer, ₼ (leave empty for the exact cash portion)",
    "Müştəridən alınan nağd, ₼": "Cash received from the customer, ₼",
    "Dəqiq məbləğ": "Exact amount",
    "Terminalda / bank tətbiqində {0} ₼ ödənişin keçdiyini yoxlayın, sonra təsdiqləyin.": "Check on the terminal / in the banking app that the {0} ₼ payment went through, then confirm.",
    "Yazılır…": "Saving…",
    "Təsdiqlə və çek çap et (Enter)": "Confirm and print receipt (Enter)",
    "Nağd hissə: {0} ₼": "Cash portion: {0} ₼",
    "Qaytarılacaq": "Change",
    "Məhsul": "Product",
    "Mağaza barkodu": "Store barcode",
    "Say": "Qty",
    "Qiymət": "Price",
    "Cəm": "Total",
    "Sil": "Delete",
    "Endirim (F4)": "Discount (F4)",
    "Ləğv (Esc)": "Cancel (Esc)",
    "Çek": "Receipt",
    "↑/↓ sətir seçimi · + / − say · Del və ya zibil ikonu: sətri silmək (menecer təsdiqi: PIN və ya sorğu).": "↑/↓ select line · + / − quantity · Del or trash icon: remove the line (manager approval: PIN or request).",
    "Ödəniş": "Payment",
    "Ara cəm": "Subtotal",
    "Endirim": "Discount",
    "Yekun": "Total",
    "Nağd": "Cash",
    "Bank": "Bank",
    "Qarışıq": "Split",
    "Nağd alınan": "Cash received",
    "Qaytarılan": "Returned",
    "DUBLİKAT": "DUPLICATE",
    "VÖEN": "VÖEN",
    "Çek №": "Receipt #",
    "Tarix": "Date",
    "Kassir": "Cashier",
    "Endirim {0}%": "Discount {0}%",
    "YEKUN": "TOTAL",
    "Qaytarma {0} gün ərzində, çeklə": "Returns within {0} days with the receipt",
    "Bu çek fiskal çek deyil": "This is not a fiscal receipt",
    "QAYTARMA ÇEKİ": "RETURN RECEIPT",
    "İlkin çek №": "Original receipt #",
    "Təsdiqləyən": "Approved by",
    "ÇAP SINAĞI": "TEST PRINT",
    "Kağız {0} mm · çap sahəsi {1} mm": "Paper {0} mm · print area {1} mm",
    "← bütün çərçivə görünməlidir →": "← the whole frame must be visible →",
    "{0} dpi · zolaq {1} mm": "{0} dpi · bar {1} mm",
    "80 mm (XP-80, XP-N160 …)": "80 mm (XP-80, XP-N160 …)",
    "58 mm (XP-58 …)": "58 mm (XP-58 …)",
    "203 dpi (adətən)": "203 dpi (usual)",
    "300 dpi": "300 dpi",
    "Tətbiq kağız ölçüsünü verir (tövsiyə)": "The app sets the paper size (recommended)",
    "Çap sürücüsünün ölçüsü": "Print driver's size",
    "Digər ölçü…": "Other size…",
    "203 dpi (XP-365B, XP-420B …)": "203 dpi (XP-365B, XP-420B …)",
    "Tətbiq etiket ölçüsünü verir (tövsiyə)": "The app sets the label size (recommended)",
    "En, mm": "Width, mm",
    "Hündürlük, mm": "Height, mm",
    "Etiketdə barkod zolağı: {0} mm ({1} nöqtə), eni {2} mm.{3}": "Barcode bar on the label: {0} mm ({1} dots), width {2} mm.{3}",
    "Etiket çox dardır: barkod oxunmaya bilər, daha geniş etiket seçin.": "The label is too narrow: the barcode may not scan, choose a wider label.",
    "Çap ayarları (bu cihaz üçün)": "Print settings (for this device)",
    "Çek printeri (termo)": "Receipt printer (thermal)",
    "Kağız eni": "Paper width",
    "Çap sıxlığı": "Print resolution",
    "Kağız ölçüsü": "Paper size",
    "Çekdən sonra boşluq, mm": "Feed after receipt, mm",
    "Çekin dili": "Receipt language",
    "Test çeki çap et": "Print test receipt",
    "Etiket printeri": "Label printer",
    "Etiket ölçüsü": "Label size",
    "Test etiketi çap et": "Print test label",
    "Çap pəncərəsində: Printer — Xprinter, Miqyas — 100%, Kənar boşluqlar — Yoxdur, Başlıq və sonluq — söndürülü. Test çapında çərçivə tam görünmürsə, kənar boşluğu və ya \"Kağız ölçüsü\" seçimini dəyişin.": "In the print dialog: Printer — Xprinter, Scale — 100%, Margins — None, Headers and footers — off. If the frame is not fully visible in the test print, change the margins or the \"Paper size\" option.",
    "Yadda saxla": "Save",
    "Çap ayarları yadda saxlanıldı": "Print settings saved",
    "Eyni mağaza barkodu iki məhsulda: \"{0}\" və \"{1}\" ({2})": "The same store barcode on two products: \"{0}\" and \"{1}\" ({2})",
    "Çek № {0} iki cihazda verilib (hər ikisi saxlanıldı)": "Receipt #{0} was issued on two devices (both were kept)",
    "Hadisə tətbiq olunmadı ({0}): {1}": "Event not applied ({0}): {1}",
    "Satış etmək": "Make sales",
    "Endirimi təsdiqləmək": "Approve discounts",
    "Çekdən sətir silmək": "Remove lines from a receipt",
    "Qaytarma sorğusu": "Return request",
    "Qaytarmanı təsdiqləmək": "Approve returns",
    "Növbə açıb bağlamaq": "Open and close shifts",
    "Məhsullara baxmaq": "View products",
    "Məhsul yaratmaq və dəyişmək": "Create and edit products",
    "Mal qəbul etmək (qalığı artırmaq)": "Receive goods (increase stock)",
    "Satış qiymətini təyin etmək": "Set the sale price",
    "Alış qiymətini görmək": "See the purchase price",
    "Etiket çap etmək": "Print labels",
    "Hesabatlara baxmaq": "View reports",
    "Təchizatçılara və təchizatçı hesabatına baxmaq": "View suppliers and the supplier report",
    "Təchizatçı əlavə etmək və dəyişmək": "Add and edit suppliers",
    "İstifadəçiləri idarə etmək": "Manage users",
    "İcazə matrisini dəyişmək": "Change the permission matrix",
    "Admin": "Admin",
    "Menecer": "Manager",
    "Mühasib": "Accountant",
    "Endirim faizi 0-dan böyük olmalıdır": "The discount percentage must be greater than 0",
    "Endirim {0}%-dən çox ola bilməz": "The discount cannot exceed {0}%",
    "Çek boşdur": "The receipt is empty",
    "Alınan məbləği yazın": "Enter the amount received",
    "Alınan məbləğ yekundan azdır": "The amount received is less than the total",
    "POS kart və ya köçürmə seçin": "Choose POS card or transfer",
    "Bank hissəsinin növünü seçin": "Choose the type of the bank portion",
    "Bank hissəsini yazın": "Enter the bank portion",
    "Bank hissəsi yekundan az olmalıdır, əks halda \"Bank\" seçin": "The bank portion must be less than the total, otherwise choose \"Bank\"",
    "Nağd alınan məbləğ nağd hissədən azdır": "The cash received is less than the cash portion",
    "Ödəniş üsulu seçilməyib": "No payment method selected",
    "İstifadəçi": "User",
    "Daxil ol": "Sign in",
    "Mağaza idarəetmə sistemi": "Store management system",
    "PIN": "PIN",
    "İstifadəçini seçin": "Select a user",
    "Server qoşulub · istifadəçilər və məlumat avtomatik yenilənir": "Server connected · users and data update automatically",
    "Bu cihazı serverə qoş": "Connect this device to the server",
    "Başqa cihazda artıq işləyirsinizsə, bunu edin: istifadəçilər, məhsullar və çeklər oradan yüklənəcək.": "If you already work on another device, do this: users, products and receipts will be loaded from there.",
    "Ünvanı və açarı (SYNC_TOKEN) yazın. Məlumat serverdən yüklənəcək, bir neçə saniyə çəkə bilər.": "Enter the address and the key (SYNC_TOKEN). The data will be loaded from the server; this may take a few seconds.",
    "Apps Script veb tətbiq ünvanı": "Apps Script web app address",
    "Sinxron açarı": "Sync key",
    "Qoş və yüklə": "Connect and load",
    "Yoxlanılır və yüklənir…": "Checking and loading…",
    "Qoşuldu · {0} qeyd yükləndi": "Connected · {0} records loaded",
    "Yeni PIN təyin edin": "Set a new PIN",
    "İşə başlamazdan əvvəl yalnız sizə məlum olan 4–8 rəqəmli PIN seçin.": "Before you start, choose a 4–8 digit PIN that only you know.",
    "Hazırkı PIN": "Current PIN",
    "Yeni PIN": "New PIN",
    "Yeni PIN təkrar": "Repeat the new PIN",
    "Saxla və davam et": "Save and continue",
    "Yeni PIN-lər eyni deyil": "The new PINs do not match",
    "PIN dəyişdirildi": "PIN changed",
    "Təsdiq sorğuları": "Approval requests",
    "Gözləyən sorğu yoxdur.": "No pending requests.",
    "Təsdiqləndi": "Approved",
    "Rədd edildi": "Rejected",
    "Rədd et": "Reject",
    "Təsdiqlə": "Approve",
    "Ad, mağaza və ya istehsalçı barkodu": "Name, store barcode or manufacturer barcode",
    "Nümunə məhsullar əlavə olundu": "Sample products added",
    "Sınaq üçün nümunə məhsullar əlavə et": "Add sample products for testing",
    "Uyğun məhsul yoxdur": "No matching products",
    "Hələ məhsul yoxdur": "No products yet",
    "köhnə qalıq": "old stock",
    "Aktiv": "Active",
    "Passiv": "Inactive",
    "Dəyiş": "Edit",
    "Qəbul": "Receive",
    "Partiyalar": "Lots",
    "Etiket": "Label",
    "Axtarış": "Search",
    "Yeni məhsul": "New product",
    "İstehsalçı barkodu": "Manufacturer barcode",
    "Satış ₼": "Sale ₼",
    "Orta maya ₼": "Avg. cost ₼",
    "Qalıq": "Stock",
    "Təchizatçı (qalıq)": "Supplier (stock)",
    "Status": "Status",
    "Ad *": "Name *",
    "Kateqoriya": "Category",
    "Brend": "Brand",
    "Yaş qrupu": "Age group",
    "məs. 3+": "e.g. 3+",
    "İstehsalçı barkodu (nəzarət üçün, uzunluq məhdud deyil)": "Manufacturer barcode (for reference, length is not limited)",
    "Satış qiyməti, ₼ *": "Sale price, ₼ *",
    "Alış qiyməti, ₼": "Purchase price, ₼",
    "Minimum qalıq": "Minimum stock",
    "Satış qiymətini yalnız Menecer və Admin təyin edir.": "Only Manager and Admin set the sale price.",
    "Mağaza barkodu:": "Store barcode:",
    "(dəyişmir)": "(does not change)",
    "Mağaza barkodu yadda saxlayanda avtomatik veriləcək.": "The store barcode will be assigned automatically when you save.",
    "Satışda aktivdir": "Active for sale",
    "Məhsulu dəyiş": "Edit product",
    "Satış qiyməti səhvdir": "Invalid sale price",
    "Alış qiyməti səhvdir": "Invalid purchase price",
    "Məhsul yaradıldı · {0}": "Product created · {0}",
    "Yadda saxlanıldı": "Saved",
    "Qaimə №, izah": "Invoice no., note",
    "— təchizatçı seçin —": "— select a supplier —",
    "— təchizatçı yoxdur —": "— no suppliers —",
    "FIFO: hər satış ən köhnə partiyadan çıxır, hesabatda təchizatçıya görə görünür.": "FIFO: each sale is taken from the oldest lot; the report shows it by supplier.",
    "Hələ təchizatçı yoxdur. Yeni təchizatçı əlavə edin; təchizatçısız qəbul \"köhnə qalıq\" kimi sayılır.": "There are no suppliers yet. Add a new supplier; receiving without a supplier counts as \"old stock\".",
    "+ Yeni təchizatçı": "+ New supplier",
    "Mal qəbulu — {0}": "Goods receipt — {0}",
    "Hazırkı qalıq: {0}. Hər qəbul ayrıca partiyadır (təchizatçı, say, alış qiyməti).": "Current stock: {0}. Each receipt is a separate lot (supplier, quantity, purchase price).",
    "Təchizatçı": "Supplier",
    "Alış qiyməti (ədəd), ₼": "Purchase price (per unit), ₼",
    "Qeyd": "Note",
    "Qəbul et": "Receive",
    "Təchizatçını seçin": "Select a supplier",
    "Qalıq: {0}": "Stock: {0}",
    "Şirkət və ya şəxs adı": "Company or person name",
    "VÖEN, ünvan, şərtlər…": "VÖEN, address, terms…",
    "Təchizatçını dəyiş": "Edit supplier",
    "Yeni təchizatçı": "New supplier",
    "Telefon": "Phone",
    "Partiyalar (FIFO) — {0}": "Lots (FIFO) — {0}",
    "Bu məhsul üzrə qəbul yoxdur.": "There are no receipts for this product.",
    "Qəbul tarixi": "Receipt date",
    "Alış ₼": "Cost ₼",
    "Köhnə qalıq": "Old stock",
    "Təchizatçısız": "No supplier",
    "Satış ən köhnə partiyadan çıxır. \"Qalıq\" sütunu hələ satılmamış hissədir.": "Sales are taken from the oldest lot. The \"Stock\" column is the part not yet sold.",
    "Etiket {0} × {1} mm · {2} dpi · barkod zolağı {3} mm{4}": "Label {0} × {1} mm · {2} dpi · barcode bar {3} mm{4}",
    "— etiket dardır, barkod oxunmaya bilər": "— the label is narrow, the barcode may not scan",
    "Etiket çapı": "Label printing",
    "Etiket sayı": "Number of labels",
    "Çap ayarları": "Print settings",
    "Çap et": "Print",
    "Bu ay": "This month",
    "Bu gün": "Today",
    "Dünən": "Yesterday",
    "Keçən ay": "Last month",
    "Bütün vaxt": "All time",
    "Seçilmiş tarixlər": "Selected dates",
    "Hələ təchizatçı yoxdur": "No suppliers yet",
    "Söndürülüb": "Disabled",
    "Redaktə": "Edit",
    "Söndürüldü": "Disabled",
    "Aktiv edildi": "Enabled",
    "Diqqət: {0} ədəd mal satılandan artıq qaytarılıb (məsələn, iki cihaz eyni çekin eyni sətrini oflayn qaytarıb). Qaytarmalar bölməsində həmin çeki yoxlayın; pul iki dəfə qaytarılmış ola bilər.": "Warning: {0} units were returned beyond what was sold (for example, two devices returned the same line of the same receipt offline). Check that receipt in the Returns section; the money may have been refunded twice.",
    "Satılan": "Sold",
    "Xalis ədəd": "Net qty",
    "Gəlir ₼": "Revenue ₼",
    "Maya (FIFO) ₼": "Cost (FIFO) ₼",
    "Mənfəət ₼": "Profit ₼",
    "Qalıq (ədəd)": "Stock (pcs)",
    "Qalığın dəyəri ₼": "Stock value ₼",
    "Bu dövrdə məlumat yoxdur": "No data for this period",
    "Cəmi": "Total",
    "{0} — məhsullar": "{0} — products",
    "Xalis": "Net",
    "Maya ₼": "Cost ₼",
    "Gəlir": "Revenue",
    "Maya (FIFO)": "Cost (FIFO)",
    "Mənfəət": "Profit",
    "Ad": "Name",
    "Vəziyyət": "Status",
    "Hansı təchizatçının malından nə qədər satılıb": "How much has been sold from each supplier's goods",
    "Excel üçün CSV": "CSV for Excel",
    "Dövr": "Period",
    "Başlanğıc": "Start",
    "Son": "End",
    "Satış FIFO ilədir: hər çek ən köhnə partiyadan çıxır. Gəlir endirimdən sonrakı məbləğdir, qaytarmalar çıxılır. \"Təchizatçısız\" — sistemə köçməzdən əvvəlki qalıq və ya qəbuldan əvvəl (mənfi qalıqla) satılan mal. Oflayn cihaz sonra sinxronlaşanda bölgü təchizatçılar arasında düzələ bilər, cəmlər dəyişmir.": "Sales follow FIFO: each receipt is taken from the oldest lot. Revenue is the amount after discount, returns are deducted. \"No supplier\" means stock that existed before moving to the system, or goods sold before receipt (with negative stock). When an offline device syncs later, the split between suppliers may be corrected; the totals do not change.",
    "Çek tapılmadı": "Receipt not found",
    "({0}% endirim)": "({0}% discount)",
    "Keçən gün": "Days elapsed",
    "Çekin qaytarma müddəti bitib: {0} gün keçib (limit {1} gün).": "The return period for this receipt has expired: {0} days have passed (limit {1} days).",
    "Qaytarılan say: {0}": "Return quantity: {0}",
    "\"{0}\": ən çox {1} ədəd qaytarmaq olar (satılıb {2})": "\"{0}\": at most {1} can be returned (sold {2})",
    "məs. zədəli, uyğun gəlmədi": "e.g. damaged, did not fit",
    "Satılıb": "Sold",
    "Qaytarılıb": "Returned",
    "Qaytarılır": "Returning",
    "Səbəb": "Reason",
    "Qaytarılacaq say yazın": "Enter the quantity to return",
    "\"{0}\": satılıb {1}, əvvəl qaytarılıb {2} — ən çox {3} ədəd qaytarmaq olar": "\"{0}\": sold {1}, previously returned {2} — at most {3} can be returned",
    "Çek № {0} üzrə {1} ₼ qaytarılır.": "{1} ₼ is being refunded for receipt #{0}.",
    "Qaytarmanı təsdiqlə": "Approve return",
    "{0} qaytarma istəyir. Çek № {1} üzrə {2} ₼ qaytarılır.": "{0} requests a return. {2} ₼ is refunded for receipt #{1}.",
    "Qaytarıldı: {0} ₼{1}": "Refunded: {0} ₼{1}",
    "(nağd {0})": "(cash {0})",
    "Qaytar": "Return",
    "Çekin barkodunu oxudun və ya çek nömrəsini yazın": "Scan the receipt barcode or type the receipt number",
    "Açıq növbə yoxdur. Kassa ekranından açın.": "There is no open shift. Open one from the checkout screen.",
    "Sayılmış məbləği yazın": "Enter the counted amount",
    "Növbə yoxlanılır və bağlanır…": "Checking and closing the shift…",
    "Növbə bağlandı. Fərq: {0} ₼": "Shift closed. Difference: {0} ₼",
    "Bağla və Z hesabatı çap et": "Close and print Z report",
    "Açılıb: {0} · {1}": "Opened: {0} · {1}",
    "Çek sayı": "Number of receipts",
    "Satış (endirimdən əvvəl)": "Sales (before discount)",
    "Nağd satış": "Cash sales",
    "Qaytarmalar": "Returns",
    "Kassaya mədaxil": "Cash in",
    "Kassadan məxaric": "Cash out",
    "Başlanğıc nağd": "Opening cash",
    "Kassada olmalı nağd": "Cash expected in the till",
    "Növbəni bağla": "Close the shift",
    "Sayılmış nağd, ₼": "Counted cash, ₼",
    "Fərq varsa izah": "Explanation if there is a difference",
    "Bank cəmlərini (POS və köçürmə) gün sonu bank çıxarışı ilə tutuşdurun.": "Reconcile the bank totals (POS and transfers) with the bank statement at the end of the day.",
    "Məbləğ, ₼": "Amount, ₼",
    "Məxarici təsdiqlə": "Approve cash out",
    "{0} ₼ kassadan çıxarılır: {1}": "{0} ₼ is being taken from the till: {1}",
    "{0} kassadan məxaric istəyir: {1} ₼ ({2})": "{0} requests a cash-out of {1} ₼ ({2})",
    "Qeydə alındı": "Recorded",
    "Açılış": "Opened",
    "Bağlanış": "Closed",
    "Satış": "Sales",
    "Köçürmə": "Transfer",
    "Gözlənilən nağd": "Expected cash",
    "Sayılmış nağd": "Counted cash",
    "Fərq": "Difference",
    "İzah": "Explanation",
    "Z HESABATI": "Z REPORT",
    "Yekun ₼": "Total ₼",
    "Hələ satış yoxdur": "No sales yet",
    "Dublikat çek": "Duplicate receipt",
    "Çek № {0} \"DUBLİKAT\" qeydi ilə çap olunur.": "Receipt #{0} is printed marked \"DUPLICATE\".",
    "Dublikat": "Duplicate",
    "Rollar və icazələr": "Roles and permissions",
    "Hansı rolun hansı əməliyyata icazəsi olduğunu yalnız Admin dəyişir. Hər dəyişiklik audit jurnalına yazılır.": "Only the Admin can change which role may do what. Every change is written to the audit log.",
    "İcazə": "Permission",
    "İcazələr yadda saxlanıldı": "Permissions saved",
    "Mağaza adı": "Store name",
    "Ünvan": "Address",
    "Kassa adı": "Register name",
    "Sinxron açarı (SYNC_TOKEN)": "Sync key (SYNC_TOKEN)",
    "Dəyişmək üçün yazın": "Type to change",
    "Saxlanılıb · dəyişmək üçün yazın": "Saved · type to change",
    "server qoşulub": "server connected",
    "server qoşulmayıb (yalnız bu cihaz)": "server not connected (this device only)",
    "· göndərilməmiş: {0}": "· not sent: {0}",
    "· son sinxron: {0}": "· last sync: {0}",
    "Son xəta: {0}": "Last error: {0}",
    "Sinxron alınmadı: {0}": "Sync failed: {0}",
    "Ünvan yoxdur və ya oflayn": "No address or offline",
    "{0} qeyd göndərildi, {1} qeyd alındı": "{0} records sent, {1} received",
    "Mağaza və server": "Store and server",
    "Ünvan boşdursa, sistem yalnız bu kompyuterdə işləyir. Hər yeni brauzer/cihaz bir dəfə qoşulmalıdır (giriş ekranında \"Bu cihazı serverə qoş\").": "If the address is empty, the system works on this computer only. Each new browser/device must be connected once (on the sign-in screen: \"Connect this device to the server\").",
    "Bağlantını yoxla": "Test connection",
    "İndi sinxronlaşdır": "Sync now",
    "{0} üçün müvəqqəti PIN bir dəfə göstərilir. İndi ötürün: ilk girişdə özünün yeni PIN-ini seçəcək.": "The temporary PIN for {0} is shown once. Hand it over now: at first sign-in the user will choose their own new PIN.",
    "PIN dəyişməlidir": "PIN must be changed",
    "PIN-i sıfırla": "Reset PIN",
    "Məs. Elvin Babayev": "E.g. Elvin Babayev",
    "Yeni istifadəçi": "New user",
    "Ad və soyad": "First and last name",
    "Rol": "Role",
    "Müvəqqəti PIN yaradılacaq; istifadəçi ilk girişdə öz PIN-ini seçir.": "A temporary PIN will be generated; the user chooses their own PIN at first sign-in.",
    "Yarat": "Create",
    "İstifadəçi yaradıldı": "User created",
    "Redaktə — {0}": "Edit — {0}",
    "Öz rolunuzu dəyişə bilməzsiniz.": "You cannot change your own role.",
    "Rol dəyişəndə istifadəçinin açıq cihazında menyu və icazələr bir neçə saniyəyə yenilənir.": "When the role changes, the menu and permissions on the user's open device update within a few seconds.",
    "Dəyişiklik yoxdur": "No changes",
    "İstifadəçi artıq daxil ola bilməyəcək, açıq cihazlarda isə bir neçə saniyəyə çıxış edəcək. Keçmiş çeklər və hesabatlar saxlanılır.": "The user will no longer be able to sign in, and will be signed out on open devices within a few seconds. Past receipts and reports are kept.",
    "İstifadəçi yenidən daxil ola biləcək (PIN dəyişməyibsə köhnə PIN ilə).": "The user will be able to sign in again (with the old PIN, if it was not changed).",
    "PIN-i sıfırla — {0}": "Reset PIN — {0}",
    "Müvəqqəti PIN yaradılacaq. İstifadəçi ilk girişdə özünün yeni PIN-ini seçəcək. Köhnə PIN dərhal etibarsız olur.": "A temporary PIN will be generated. At first sign-in the user will choose a new PIN. The old PIN stops working immediately.",
    "Sıfırla": "Reset",
    "Müvəqqəti PIN": "Temporary PIN",
    "İstifadəçilər": "Users",
    "+ Yeni istifadəçi": "+ New user",
    "Hesabınız söndürülüb. Yenidən daxil olun": "Your account has been disabled. Please sign in again",
    "Bu əməliyyata icazəniz yoxdur: {0}": "You do not have permission for this action: {0}",
    "Nömrə ehtiyatı bitib. İnternetə qoşulun və bir neçə saniyə gözləyin": "The number reserve has run out. Connect to the internet and wait a few seconds",
    "İstifadəçi tapılmadı": "User not found",
    "Çox səhv cəhd. {0} dəqiqə gözləyin": "Too many wrong attempts. Wait {0} minutes",
    "PIN səhvdir": "Wrong PIN",
    "PIN 4–8 rəqəm olmalıdır": "The PIN must be 4–8 digits",
    "Yeni PIN köhnə PIN ilə eyni ola bilməz": "The new PIN cannot be the same as the old one",
    "Çox sadə PIN seçməyin": "Do not choose a PIN that is too simple",
    "Köhnə PIN səhvdir": "The old PIN is wrong",
    "Ad ən azı 2 simvol olmalıdır": "The name must be at least 2 characters",
    "Ad 40 simvoldan uzun ola bilməz": "The name cannot be longer than 40 characters",
    "Bu adda istifadəçi artıq var": "A user with this name already exists",
    "Rol seçin": "Select a role",
    "Rol səhvdir": "Invalid role",
    "Öz hesabınızı söndürə bilməzsiniz": "You cannot disable your own account",
    "Sistemdə ən azı bir aktiv Admin qalmalıdır": "At least one active Admin must remain in the system",
    "PIN yanlışdır və ya bu şəxsin təsdiq icazəsi yoxdur": "The PIN is wrong or this person has no approval permission",
    "Məhsulun adı boşdur": "The product name is empty",
    "Satış qiyməti 0-dan böyük olmalıdır": "The sale price must be greater than 0",
    "İstehsalçı barkodunda boşluq ola bilməz": "A manufacturer barcode cannot contain spaces",
    "Bu, mağaza və ya çek barkodudur, istehsalçı barkodu deyil": "This is a store or receipt barcode, not a manufacturer barcode",
    "Satış qiymətini yalnız Menecer və Admin təyin edir": "Only Manager and Admin set the sale price",
    "Bu istehsalçı barkodu artıq var: {0}": "This manufacturer barcode already exists: {0}",
    "Məhsul tapılmadı": "Product not found",
    "Təchizatçının adı ən azı 2 simvol olmalıdır": "The supplier name must be at least 2 characters",
    "Ad 60 simvoldan uzun ola bilməz": "The name cannot be longer than 60 characters",
    "Bu adda təchizatçı artıq var": "A supplier with this name already exists",
    "Telefon çox uzundur": "The phone number is too long",
    "Qeyd 300 simvoldan uzun ola bilməz": "The note cannot be longer than 300 characters",
    "Təchizatçı tapılmadı": "Supplier not found",
    "Say müsbət tam ədəd olmalıdır": "The quantity must be a positive whole number",
    "Təchizatçı tapılmadı və ya söndürülüb": "Supplier not found or disabled",
    "Silinmiş təchizatçı": "Deleted supplier",
    "Təchizatçısız (köhnə qalıq / mənfi satış)": "No supplier (old stock / negative-stock sale)",
    "Başlanğıc nağdı yazın": "Enter the opening cash",
    "Artıq açıq növbə var": "A shift is already open",
    "Əvvəlki növbədən qalıq {0} ₼ idi. Fərqli məbləğ üçün izah yazın": "The previous shift's balance was {0} ₼. Write an explanation for a different amount",
    "Səbəbi yazın": "Enter the reason",
    "Kassadan məxaric menecer təsdiqi tələb edir": "A cash-out requires manager approval",
    "Növbə açıq deyil": "The shift is not open",
    "Kassa fərqi var ({0} ₼). İzah yazın": "There is a cash difference ({0} ₼). Write an explanation",
    "Açıq növbə yoxdur": "There is no open shift",
    "Sinxronlaşmamış {0} qeyd var. İnternet qayıdana qədər növbə bağlanmır (FR-104)": "There are {0} unsynced records. The shift cannot be closed until the internet is back (FR-104)",
    "Endirim menecer tərəfindən təsdiqlənməyib": "The discount has not been approved by a manager",
    "Satış üçün növbəni açın": "Open a shift to sell",
    "Məhsul satışda deyil": "The product is not for sale",
    "Say səhvdir: {0}": "Invalid quantity: {0}",
    "\"{0}\" qalığı yoxdur və artıq {1} mənfi çekdə satılıb. Mal qəbulu daxil edin": "\"{0}\" is out of stock and has already been sold in {1} negative-stock receipts. Enter a goods receipt",
    "Çekin qaytarma müddəti bitib ({0} gün keçib, limit {1} gün)": "The return period for this receipt has expired ({0} days have passed, limit {1} days)",
    "Sətir tapılmadı": "Line not found",
    "\"{0}\": say tam müsbət ədəd olmalıdır": "\"{0}\": the quantity must be a positive whole number",
    "Qaytarma menecer təsdiqi tələb edir": "A return requires manager approval",
    "Qaytarma üçün növbəni açın": "Open a shift to make a return",
    "\"{0}\" üzrə ən çox {1} ədəd qaytarmaq olar": "\"{0}\": at most {1} can be returned",
    "Qaytarılacaq məhsul seçin": "Select the product to return",
    "Admin icazə idarəsini özündən götürə bilməz": "The Admin cannot remove their own permission-management right",
    "Qərar səhvdir": "Invalid decision",
    "Sorğu tapılmadı": "Request not found",
    "Öz sorğunuzu təsdiqləyə bilməzsiniz": "You cannot approve your own request",
    "Sorğuya artıq cavab verilib": "The request has already been answered",
    "Sorğunun vaxtı bitib": "The request has expired",
    "Ünvan boşdur": "The address is empty",
    "Bu /dev ünvanıdır, o yalnız sizin brauzerinizdə işləyir. Deploy → Manage deployments bölməsindən /exec ilə bitən ünvanı götürün": "This is a /dev address; it only works in your own browser. In Deploy → Manage deployments take the address ending in /exec",
    "Bu Apps Script redaktorunun linkidir. Deploy → Manage deployments → Web app URL lazımdır": "This is a link to the Apps Script editor. You need Deploy → Manage deployments → Web app URL",
    "Ünvan https://script.google.com/macros/s/…/exec formasında olmalıdır": "The address must look like https://script.google.com/macros/s/…/exec",
    "{0}. İnterneti yoxlayın; Apps Script bəzən yavaş cavab verir, sinxron özü təkrar cəhd edəcək": "{0}. Check the internet connection; Apps Script sometimes responds slowly, sync will retry by itself",
    "Server cavab vermədi. Ən çox səbəb: Deploy-da \"Who has access\" = \"Anyone\" deyil (yalnız Google hesabına girmiş brauzerdə işləyir, digər brauzerdə yox). Yoxlama: ünvanı gizli pəncərədə açın, {\"ok\":true} görünməlidir. Kodu dəyişəndən sonra \"New version\" deploy etmək də lazımdır": "The server did not respond. Most common cause: \"Who has access\" in Deploy is not \"Anyone\" (it only works in a browser signed in to a Google account, not in others). Check: open the address in a private window, you should see {\"ok\":true}. After changing the code you must also deploy a \"New version\"",
    "Server JSON əvəzinə səhifə qaytardı (çox güman Google giriş səhifəsi və ya Apps Script limiti). Deploy-da \"Who has access\" = \"Anyone\" olmalıdır": "The server returned a page instead of JSON (most likely the Google sign-in page or an Apps Script limit). \"Who has access\" in Deploy must be \"Anyone\"",
    "Server {0} san ərzində cavab vermədi": "The server did not respond within {0} s",
    "Sorğu dayandırıldı": "The request was aborted",
    "Server {0}": "Server {0}",
    "Açar uyğun gəlmir: tətbiqdəki açar Script properties-dəki SYNC_TOKEN ilə eyni olmalıdır": "The key does not match: the key in the app must be the same as SYNC_TOKEN in Script properties",
    "Server xətası": "Server error",
    "Cavab gəldi, amma bu, mağaza skripti deyil": "A response came back, but it is not the store script",
    "Skriptdə SYNC_TOKEN təyin olunmayıb (Project Settings → Script properties)": "SYNC_TOKEN is not set in the script (Project Settings → Script properties)",
    "Skriptin köhnə versiyası işləyir. Yeni Code.gs-i yapışdırın və Deploy → Manage deployments → Edit → New version seçin": "An old version of the script is running. Paste the new Code.gs and choose Deploy → Manage deployments → Edit → New version",
    "Cədvəllərdə çatışmayan vərəqlər: {0}. setup() funksiyasını işə salın": "Sheets are missing from the spreadsheet: {0}. Run the setup() function",
    "Bağlantı işləyir{0}": "Connection works{0}",
    ". Diqqət: skript köhnədir (v{0}). {1}{2}telefona bildiriş üçün yeni Code.gs-i yapışdırın, setup() işlədin və \"New version\" deploy edin (tətbiq bu olmadan da işləyir, məlumat Events vərəqində saxlanılır)": ". Warning: the script is outdated (v{0}). {1}{2}for phone notifications paste the new Code.gs, run setup() and deploy a \"New version\" (the app works without this too, data is kept in the Events sheet)",
    "Sürətli sinxron və keş düzəlişi,": "faster sync and cache fix,",
    "təchizatçı/partiya cədvəllərinin Sheets-ə yazılması,": "writing the supplier/lot sheets to Sheets,",
    "Server qoşulmayıb": "The server is not connected",
    "Açarı (SYNC_TOKEN) yazın": "Enter the key (SYNC_TOKEN)",
    "Ləğv et": "Cancel",
    "Menecer PIN-ini yazın və ya sorğu göndərin: menecer öz cihazında təsdiqləyəcək.": "Enter the manager's PIN or send a request: the manager will approve on their own device.",
    "Menecer PIN-ini yazın.": "Enter the manager's PIN.",
    "Menecer PIN-i": "Manager PIN",
    "Menecer təsdiqlədi": "The manager approved",
    "Menecer sorğunu rədd etdi": "The manager rejected the request",
    "Sorğunun vaxtı bitdi": "The request timed out",
    "Menecerə sorğu göndər": "Send a request to the manager",
    "Sorğu üçün internet lazımdır. Menecer PIN-i ilə təsdiqləyin": "A request needs the internet. Approve with the manager's PIN",
    "Sorğu menecerə göndərildi, cavab gözlənilir: {0}": "Request sent to the manager, waiting for a reply: {0}",
    "Sorğu ləğv edildi": "Request cancelled",
    "Sorğu menecerə göndərildi": "Request sent to the manager",
    "Qaytarılan@@change": "Change",
    "JSON səhvdir": "Invalid JSON",
    "Naməlum əməliyyat": "Unknown operation",
    "Naməlum açar": "Unknown key",
    "Server məşğuldur, sonra təkrar olunacaq": "Server is busy, will retry later",
    "Bildiriş ünvanı tanınmır": "Notification endpoint not recognised",
    "Bu cihaz bildiriş üçün qeydiyyatdan keçməyib": "This device is not registered for notifications"
  });
})(typeof window !== 'undefined' ? window : globalThis);
